part of '../../raylib_dartified_web.dart';

class RaylibGui extends RaylibModuleWasm with RaylibGuiModuleExtras<Raylib> {
  late final JSFunction GuiEnable;
  late final JSFunction GuiDisable;
  late final JSFunction GuiLock;
  late final JSFunction GuiUnlock;
  late final JSFunction GuiIsLocked;
  late final JSFunction GuiSetAlpha;
  late final JSFunction GuiSetState;
  late final JSFunction GuiGetState;
  late final JSFunction GuiSetFont;
  late final JSFunction GuiGetFont;
  late final JSFunction GuiSetStyle;
  late final JSFunction GuiGetStyle;
  late final JSFunction GuiLoadStyle;
  late final JSFunction GuiLoadStyleDefault;
  late final JSFunction GuiEnableTooltip;
  late final JSFunction GuiDisableTooltip;
  late final JSFunction GuiSetTooltip;
  late final JSFunction GuiIconText;
  late final JSFunction GuiSetIconScale;
  late final JSFunction GuiGetIcons;
  late final JSFunction GuiLoadIcons;
  late final JSFunction GuiDrawIcon;
  late final JSFunction GuiGetTextWidth;
  late final JSFunction GuiWindowBox;
  late final JSFunction GuiGroupBox;
  late final JSFunction GuiLine;
  late final JSFunction GuiPanel;
  late final JSFunction GuiTabBar;
  late final JSFunction GuiScrollPanel;
  late final JSFunction GuiLabel;
  late final JSFunction GuiButton;
  late final JSFunction GuiLabelButton;
  late final JSFunction GuiToggle;
  late final JSFunction GuiToggleGroup;
  late final JSFunction GuiToggleSlider;
  late final JSFunction GuiCheckBox;
  late final JSFunction GuiComboBox;
  late final JSFunction GuiDropdownBox;
  late final JSFunction GuiSpinner;
  late final JSFunction GuiValueBox;
  late final JSFunction GuiValueBoxFloat;
  late final JSFunction GuiTextBox;
  late final JSFunction GuiSlider;
  late final JSFunction GuiSliderBar;
  late final JSFunction GuiProgressBar;
  late final JSFunction GuiStatusBar;
  late final JSFunction GuiDummyRec;
  late final JSFunction GuiGrid;
  late final JSFunction GuiListView;
  late final JSFunction GuiListViewEx;
  late final JSFunction GuiMessageBox;
  late final JSFunction GuiTextInputBox;
  late final JSFunction GuiColorPicker;
  late final JSFunction GuiColorPanel;
  late final JSFunction GuiColorBarAlpha;
  late final JSFunction GuiColorBarHue;
  late final JSFunction GuiColorPickerHSV;
  late final JSFunction GuiColorPanelHSV;

  RaylibGui(super.rl) {
    GuiEnable = _module.dwrap('GuiEnable', []);
    GuiDisable = _module.dwrap('GuiDisable', []);
    GuiLock = _module.dwrap('GuiLock', []);
    GuiUnlock = _module.dwrap('GuiUnlock', []);
    GuiIsLocked = _module.dwrap('GuiIsLocked', [], n);
    GuiSetAlpha = _module.dwrap('GuiSetAlpha', [n]);
    GuiSetState = _module.dwrap('GuiSetState', [n]);
    GuiGetState = _module.dwrap('GuiGetState', [], n);
    GuiSetFont = _module.dwrap('GuiSetFont', [n]);
    GuiGetFont = _module.dwrap('GuiGetFont', [n]);
    GuiSetStyle = _module.dwrap('GuiSetStyle', [n, n, n]);
    GuiGetStyle = _module.dwrap('GuiGetStyle', [n, n], n);
    GuiLoadStyle = _module.dwrap('GuiLoadStyle', [s]);
    GuiLoadStyleDefault = _module.dwrap('GuiLoadStyleDefault', []);
    GuiEnableTooltip = _module.dwrap('GuiEnableTooltip', []);
    GuiDisableTooltip = _module.dwrap('GuiDisableTooltip', []);
    GuiSetTooltip = _module.dwrap('GuiSetTooltip', [s]);
    GuiIconText = _module.dwrap('GuiIconText', [n, s], n);
    GuiSetIconScale = _module.dwrap('GuiSetIconScale', [n]);
    GuiGetIcons = _module.dwrap('GuiGetIcons', [], n);
    GuiLoadIcons = _module.dwrap('GuiLoadIcons', [s, n], n);
    GuiDrawIcon = _module.dwrap('GuiDrawIcon', [n, n, n, n, n]);
    GuiGetTextWidth = _module.dwrap('GuiGetTextWidth', [s], n);
    GuiWindowBox = _module.dwrap('GuiWindowBox', [n, s]);
    GuiGroupBox = _module.dwrap('GuiGroupBox', [n, s], n);
    GuiLine = _module.dwrap('GuiLine', [n, s], n);
    GuiPanel = _module.dwrap('GuiPanel', [n, s], n);
    GuiTabBar = _module.dwrap('GuiTabBar', [n, n, n, n], n);
    GuiScrollPanel = _module.dwrap('GuiScrollPanel', [n, s, n, n, n], n);
    GuiLabel = _module.dwrap('GuiLabel', [n, s], n);
    GuiButton = _module.dwrap('GuiButton', [n, s], n);
    GuiLabelButton = _module.dwrap('GuiLabelButton', [n, s], n);
    GuiToggle = _module.dwrap('GuiToggle', [n, s, n], n);
    GuiToggleGroup = _module.dwrap('GuiToggleGroup', [n, s, n], n);
    GuiToggleSlider = _module.dwrap('GuiToggleSlider', [n, s, n], n);
    GuiCheckBox = _module.dwrap('GuiCheckBox', [n, s, n], n);
    GuiComboBox = _module.dwrap('GuiComboBox', [n, s, n], n);
    GuiDropdownBox = _module.dwrap('GuiDropdownBox', [n, s, n, n], n);
    GuiSpinner = _module.dwrap('GuiSpinner', [n, s, n, n, n, n], n);
    GuiValueBox = _module.dwrap('GuiValueBox', [n, s, n, n, n, n], n);
    GuiValueBoxFloat = _module.dwrap('GuiValueBoxFloat', [n, s, s, n, n], n);
    GuiTextBox = _module.dwrap('GuiTextBox', [n, n, n, n], n);
    GuiSlider = _module.dwrap('GuiSlider', [n, s, s, n, n, n], n);
    GuiSliderBar = _module.dwrap('GuiSliderBar', [n, s, s, n, n, n]);
    GuiProgressBar = _module.dwrap('GuiProgressBar', [n, s, s, n, n, n], n);
    GuiStatusBar = _module.dwrap('GuiStatusBar', [n, s], n);
    GuiDummyRec = _module.dwrap('GuiDummyRec', [n, s], n);
    GuiGrid = _module.dwrap('GuiGrid', [n, s, n, n, n], n);
    GuiListView = _module.dwrap('GuiListView', [n, s, n, n], n);
    GuiListViewEx = _module.dwrap('GuiListViewEx', [n, n, n, n, n, n], n);
    GuiMessageBox = _module.dwrap('GuiMessageBox', [n, s, s, s], n);
    GuiTextInputBox = _module.dwrap('GuiTextInputBox', [n, s, s, s, n, n, n], n);
    GuiColorPicker = _module.dwrap('GuiColorPicker', [n, s, n], n);
    GuiColorPanel = _module.dwrap('GuiColorPanel', [n, s, n], n);
    GuiColorBarAlpha = _module.dwrap('GuiColorBarAlpha', [n, s, n], n);
    GuiColorBarHue = _module.dwrap('GuiColorBarHue', [n, s, n], n);
    GuiColorPickerHSV = _module.dwrap('GuiColorPickerHSV', [n, s, n], n);
    GuiColorPanelHSV = _module.dwrap('GuiColorPanelHSV', [n, s, n], n);
  }
}