part of '../../../raylib_dartified_web.dart';

class RaylibRlgl extends RaylibModuleWasm with RaylibRlglModuleExtras<Raylib> {
  /// Choose the current matrix to be transformed
  late final WF1<void> rlMatrixMode;
  /// Push the current matrix to stack
  late final WF0<void> rlPushMatrix;
  /// Pop latest inserted matrix from stack
  late final WF0<void> rlPopMatrix;
  /// Reset current matrix to identity matrix
  late final WF0<void> rlLoadIdentity;
  /// Multiply the current matrix by a translation matrix
  late final WF3<void> rlTranslatef;
  /// Multiply the current matrix by a rotation matrix
  late final WF4<void> rlRotatef;
  /// Multiply the current matrix by a scaling matrix
  late final WF3<void> rlScalef;
  /// Multiply the current matrix by another matrix
  late final WF1<void> rlMultMatrixf;
  /// Multiply the current matrix by a perspective matrix generated by parameters
  late final WF6<void> rlFrustum;
  /// Multiply the current matrix by an orthographic matrix generated by parameters
  late final WF6<void> rlOrtho;
  /// Set the viewport area
  late final WF4<void> rlViewport;
  /// Set clip planes distances
  late final WF2<void> rlSetClipPlanes;
  /// Get cull plane distance near
  late final WF0<double> rlGetCullDistanceNear;
  /// Get cull plane distance far
  late final WF0<double> rlGetCullDistanceFar;
  /// Initialize drawing mode (how to organize vertex)
  late final WF1<void> rlBegin;
  /// Finish vertex providing
  late final WF0<void> rlEnd;
  /// Define one vertex (position) - 2 int
  late final WF2<void> rlVertex2i;
  /// Define one vertex (position) - 2 float
  late final WF2<void> rlVertex2f;
  /// Define one vertex (position) - 3 float
  late final WF3<void> rlVertex3f;
  /// Define one vertex (texture coordinate) - 2 float
  late final WF2<void> rlTexCoord2f;
  /// Define one vertex (normal) - 3 float
  late final WF3<void> rlNormal3f;
  /// Define one vertex (color) - 4 byte
  late final WF4<void> rlColor4ub;
  /// Define one vertex (color) - 3 float
  late final WF3<void> rlColor3f;
  /// Define one vertex (color) - 4 float
  late final WF4<void> rlColor4f;
  /// Enable vertex array (VAO, if supported)
  late final WF1<bool> rlEnableVertexArray;
  /// Disable vertex array (VAO, if supported)
  late final WF0<void> rlDisableVertexArray;
  /// Enable vertex buffer (VBO)
  late final WF1<void> rlEnableVertexBuffer;
  /// Disable vertex buffer (VBO)
  late final WF0<void> rlDisableVertexBuffer;
  /// Enable vertex buffer element (VBO element)
  late final WF1<void> rlEnableVertexBufferElement;
  /// Disable vertex buffer element (VBO element)
  late final WF0<void> rlDisableVertexBufferElement;
  /// Enable vertex attribute index
  late final WF1<void> rlEnableVertexAttribute;
  /// Disable vertex attribute index
  late final WF1<void> rlDisableVertexAttribute;
  /// Enable attribute state pointer
  late final WF2<void> rlEnableStatePointer;
  /// Disable attribute state pointer
  late final WF1<void> rlDisableStatePointer;
  /// Select and active a texture slot
  late final WF1<void> rlActiveTextureSlot;
  /// Enable texture
  late final WF1<void> rlEnableTexture;
  /// Disable texture
  late final WF0<void> rlDisableTexture;
  /// Enable texture cubemap
  late final WF1<void> rlEnableTextureCubemap;
  /// Disable texture cubemap
  late final WF0<void> rlDisableTextureCubemap;
  /// Set texture parameters (filter, wrap)
  late final WF3<void> rlTextureParameters;
  /// Set cubemap parameters (filter, wrap)
  late final WF3<void> rlCubemapParameters;
  /// Enable shader program
  late final WF1<void> rlEnableShader;
  /// Disable shader program
  late final WF0<void> rlDisableShader;
  /// Enable render texture (fbo)
  late final WF1<void> rlEnableFramebuffer;
  /// Disable render texture (fbo), return to default framebuffer
  late final WF0<void> rlDisableFramebuffer;
  /// Get the currently active render texture (fbo), 0 for default framebuffer
  late final WF0<int> rlGetActiveFramebuffer;
  /// Activate multiple draw color buffers
  late final WF1<void> rlActiveDrawBuffers;
  /// Blit active framebuffer to main framebuffer
  late final WF9<void> rlBlitFramebuffer;
  /// Bind framebuffer (FBO)
  late final WF2<void> rlBindFramebuffer;
  /// Enable color blending
  late final WF0<void> rlEnableColorBlend;
  /// Disable color blending
  late final WF0<void> rlDisableColorBlend;
  /// Enable depth test
  late final WF0<void> rlEnableDepthTest;
  /// Disable depth test
  late final WF0<void> rlDisableDepthTest;
  /// Enable depth write
  late final WF0<void> rlEnableDepthMask;
  /// Disable depth write
  late final WF0<void> rlDisableDepthMask;
  /// Enable backface culling
  late final WF0<void> rlEnableBackfaceCulling;
  /// Disable backface culling
  late final WF0<void> rlDisableBackfaceCulling;
  /// Color mask control
  late final WF4<void> rlColorMask;
  /// Set face culling mode
  late final WF1<void> rlSetCullFace;
  /// Enable scissor test
  late final WF0<void> rlEnableScissorTest;
  /// Disable scissor test
  late final WF0<void> rlDisableScissorTest;
  /// Scissor test
  late final WF4<void> rlScissor;
  /// Enable point mode
  late final WF0<void> rlEnablePointMode;
  /// Disable point mode
  late final WF0<void> rlDisablePointMode;
  /// Set the point drawing size
  late final WF1<void> rlSetPointSize;
  /// Get the point drawing size
  late final WF0<double> rlGetPointSize;
  /// Enable wire mode
  late final WF0<void> rlEnableWireMode;
  /// Disable wire mode
  late final WF0<void> rlDisableWireMode;
  /// Set the line drawing width
  late final WF1<void> rlSetLineWidth;
  /// Get the line drawing width
  late final WF0<double> rlGetLineWidth;
  /// Enable line aliasing
  late final WF0<void> rlEnableSmoothLines;
  /// Disable line aliasing
  late final WF0<void> rlDisableSmoothLines;
  /// Enable stereo rendering
  late final WF0<void> rlEnableStereoRender;
  /// Disable stereo rendering
  late final WF0<void> rlDisableStereoRender;
  /// Check if stereo render is enabled
  late final WF0<bool> rlIsStereoRenderEnabled;
  /// Clear color buffer with color
  late final WF4<void> rlClearColor;
  /// Clear used screen buffers (color and depth)
  late final WF0<void> rlClearScreenBuffers;
  /// Check and log OpenGL error codes
  late final WF0<void> rlCheckErrors;
  /// Set blending mode
  late final WF1<void> rlSetBlendMode;
  /// Set blending mode factor and equation (using OpenGL factors)
  late final WF3<void> rlSetBlendFactors;
  /// Set blending mode factors and equations separately (using OpenGL factors)
  late final WF6<void> rlSetBlendFactorsSeparate;
  /// Initialize rlgl (buffers, shaders, textures, states)
  late final WF2<void> rlglInit;
  /// De-initialize rlgl (buffers, shaders, textures)
  late final WF0<void> rlglClose;
  /// Load OpenGL extensions (loader function required)
  late final WF1<void> rlLoadExtensions;
  /// Get OpenGL procedure address
  late final WF1<WasmMemoryPointer<RVoid>> rlGetProcAddress;
  /// Get current OpenGL version
  late final WF0<int> rlGetVersion;
  /// Set current framebuffer width
  late final WF1<void> rlSetFramebufferWidth;
  /// Get default framebuffer width
  late final WF0<int> rlGetFramebufferWidth;
  /// Set current framebuffer height
  late final WF1<void> rlSetFramebufferHeight;
  /// Get default framebuffer height
  late final WF0<int> rlGetFramebufferHeight;
  /// Get default texture id
  late final WF0<int> rlGetTextureIdDefault;
  /// Get default shader id
  late final WF0<int> rlGetShaderIdDefault;
  /// Get default shader locations
  late final WF0<WasmMemoryPointer<RInt>> rlGetShaderLocsDefault;
  /// Load a render batch system
  late final WF3<void> rlLoadRenderBatch;
  /// Unload render batch system
  late final WF1<void> rlUnloadRenderBatch;
  /// Draw render batch data (Update->Draw->Reset)
  late final WF1<void> rlDrawRenderBatch;
  /// Set the active render batch for rlgl (NULL for default internal)
  late final WF1<void> rlSetRenderBatchActive;
  /// Update and draw internal render batch
  late final WF0<void> rlDrawRenderBatchActive;
  /// Check internal buffer overflow for a given number of vertex
  late final WF1<bool> rlCheckRenderBatchLimit;
  /// Set current texture for render batch and check buffers limits
  late final WF1<void> rlSetTexture;
  /// Load vertex array (vao) if supported
  late final WF0<int> rlLoadVertexArray;
  /// Load a vertex buffer object
  late final WF3<int> rlLoadVertexBuffer;
  /// Load vertex buffer elements object
  late final WF3<int> rlLoadVertexBufferElement;
  /// Update vertex buffer object data on GPU buffer
  late final WF4<void> rlUpdateVertexBuffer;
  /// Update vertex buffer elements data on GPU buffer
  late final WF4<void> rlUpdateVertexBufferElements;
  /// Unload vertex array (vao)
  late final WF1<void> rlUnloadVertexArray;
  /// Unload vertex buffer object
  late final WF1<void> rlUnloadVertexBuffer;
  /// Set vertex attribute data configuration
  late final WF6<void> rlSetVertexAttribute;
  /// Set vertex attribute data divisor
  late final WF2<void> rlSetVertexAttributeDivisor;
  /// Set vertex attribute default value, when attribute to provided
  late final WF4<void> rlSetVertexAttributeDefault;
  /// Draw vertex array (currently active vao)
  late final WF2<void> rlDrawVertexArray;
  /// Draw vertex array elements
  late final WF3<void> rlDrawVertexArrayElements;
  /// Draw vertex array (currently active vao) with instancing
  late final WF3<void> rlDrawVertexArrayInstanced;
  /// Draw vertex array elements with instancing
  late final WF4<void> rlDrawVertexArrayElementsInstanced;
  /// Load texture data
  late final WF5<int> rlLoadTexture;
  /// Load depth texture/renderbuffer (to be attached to fbo)
  late final WF3<int> rlLoadTextureDepth;
  /// Load texture cubemap data
  late final WF4<int> rlLoadTextureCubemap;
  /// Update texture with new data on GPU
  late final WF7<void> rlUpdateTexture;
  /// Get OpenGL internal formats
  late final WF4<void> rlGetGlTextureFormats;
  /// Get name string for pixel format
  late final WF1<WasmMemoryPointer<RChar>> rlGetPixelFormatName;
  /// Unload texture from GPU memory
  late final WF1<void> rlUnloadTexture;
  /// Generate mipmap data for selected texture
  late final WF5<void> rlGenTextureMipmaps;
  /// Read texture pixel data
  late final WF4<WasmMemoryPointer<RVoid>> rlReadTexturePixels;
  /// Read screen pixel data (color buffer)
  late final WF2<WasmMemoryPointer<RUnsignedChar>> rlReadScreenPixels;
  /// Load an empty framebuffer
  late final WF0<int> rlLoadFramebuffer;
  /// Attach texture/renderbuffer to a framebuffer
  late final WF5<void> rlFramebufferAttach;
  /// Verify framebuffer is complete
  late final WF1<bool> rlFramebufferComplete;
  /// Delete framebuffer from GPU
  late final WF1<void> rlUnloadFramebuffer;
  /// Copy framebuffer pixel data to internal buffer
  late final WF6<void> rlCopyFramebuffer;
  /// Resize internal framebuffer
  late final WF2<void> rlResizeFramebuffer;
  /// Load (compile) shader and return shader id
  late final WF2<int> rlLoadShader;
  /// Load shader from code strings
  late final WF2<int> rlLoadShaderProgram;
  /// Load shader program, using already loaded shader ids
  late final WF2<int> rlLoadShaderProgramEx;
  /// Load compute shader program
  late final WF1<int> rlLoadShaderProgramCompute;
  /// Unload shader, loaded with rlLoadShader();
  late final WF1<void> rlUnloadShader;
  /// Unload shader program
  late final WF1<void> rlUnloadShaderProgram;
  /// Get shader location uniform, requires shader program id
  late final WF2<int> rlGetLocationUniform;
  /// Get shader location attribute, requires shader program id
  late final WF2<int> rlGetLocationAttrib;
  /// Set shader value uniform
  late final WF4<void> rlSetUniform;
  /// Set shader value matrix
  late final WF2<void> rlSetUniformMatrix;
  /// Set shader value matrices
  late final WF3<void> rlSetUniformMatrices;
  /// Set shader value sampler
  late final WF2<void> rlSetUniformSampler;
  /// Set shader currently active (id and locations)
  late final WF2<void> rlSetShader;
  /// Dispatch compute shader (equivalent to *draw* for graphics pipeline)
  late final WF3<void> rlComputeShaderDispatch;
  /// Load shader storage buffer object (SSBO)
  late final WF3<int> rlLoadShaderBuffer;
  /// Unload shader storage buffer object (SSBO)
  late final WF1<void> rlUnloadShaderBuffer;
  /// Update SSBO buffer data
  late final WF4<void> rlUpdateShaderBuffer;
  /// Bind SSBO buffer
  late final WF2<void> rlBindShaderBuffer;
  /// Read SSBO buffer data (GPU->CPU)
  late final WF4<void> rlReadShaderBuffer;
  /// Copy SSBO data between buffers
  late final WF5<void> rlCopyShaderBuffer;
  /// Get SSBO buffer size
  late final WF1<int> rlGetShaderBufferSize;
  /// Bind image texture
  late final WF4<void> rlBindImageTexture;
  /// Get internal modelview matrix
  late final WF1<void> rlGetMatrixModelview;
  /// Get internal projection matrix
  late final WF1<void> rlGetMatrixProjection;
  /// Get internal accumulated transform matrix
  late final WF1<void> rlGetMatrixTransform;
  /// Get internal projection matrix for stereo render (selected eye)
  late final WF2<void> rlGetMatrixProjectionStereo;
  /// Get internal view offset matrix for stereo render (selected eye)
  late final WF2<void> rlGetMatrixViewOffsetStereo;
  /// Set a custom projection matrix (replaces internal projection matrix)
  late final WF1<void> rlSetMatrixProjection;
  /// Set a custom modelview matrix (replaces internal modelview matrix)
  late final WF1<void> rlSetMatrixModelview;
  /// Set eyes projection matrices for stereo rendering
  late final WF2<void> rlSetMatrixProjectionStereo;
  /// Set eyes view offsets matrices for stereo rendering
  late final WF2<void> rlSetMatrixViewOffsetStereo;
  /// Load and draw a cube
  late final WF0<void> rlLoadDrawCube;
  /// Load and draw a quad
  late final WF0<void> rlLoadDrawQuad;

  RaylibRlgl(super.rl) {
    rlMatrixMode                       = dwrap1('rlMatrixMode');
    rlPushMatrix                       = dwrap0('rlPushMatrix');
    rlPopMatrix                        = dwrap0('rlPopMatrix');
    rlLoadIdentity                     = dwrap0('rlLoadIdentity');
    rlTranslatef                       = dwrap3('rlTranslatef');
    rlRotatef                          = dwrap4('rlRotatef');
    rlScalef                           = dwrap3('rlScalef');
    rlMultMatrixf                      = dwrap1('rlMultMatrixf');
    rlFrustum                          = dwrap6('rlFrustum');
    rlOrtho                            = dwrap6('rlOrtho');
    rlViewport                         = dwrap4('rlViewport');
    rlSetClipPlanes                    = dwrap2('rlSetClipPlanes');
    rlGetCullDistanceNear              = dwrap0('rlGetCullDistanceNear');
    rlGetCullDistanceFar               = dwrap0('rlGetCullDistanceFar');
    rlBegin                            = dwrap1('rlBegin');
    rlEnd                              = dwrap0('rlEnd');
    rlVertex2i                         = dwrap2('rlVertex2i');
    rlVertex2f                         = dwrap2('rlVertex2f');
    rlVertex3f                         = dwrap3('rlVertex3f');
    rlTexCoord2f                       = dwrap2('rlTexCoord2f');
    rlNormal3f                         = dwrap3('rlNormal3f');
    rlColor4ub                         = dwrap4('rlColor4ub');
    rlColor3f                          = dwrap3('rlColor3f');
    rlColor4f                          = dwrap4('rlColor4f');
    rlEnableVertexArray                = dwrap1('rlEnableVertexArray');
    rlDisableVertexArray               = dwrap0('rlDisableVertexArray');
    rlEnableVertexBuffer               = dwrap1('rlEnableVertexBuffer');
    rlDisableVertexBuffer              = dwrap0('rlDisableVertexBuffer');
    rlEnableVertexBufferElement        = dwrap1('rlEnableVertexBufferElement');
    rlDisableVertexBufferElement       = dwrap0('rlDisableVertexBufferElement');
    rlEnableVertexAttribute            = dwrap1('rlEnableVertexAttribute');
    rlDisableVertexAttribute           = dwrap1('rlDisableVertexAttribute');
    rlEnableStatePointer               = dwrap2('rlEnableStatePointer');
    rlDisableStatePointer              = dwrap1('rlDisableStatePointer');
    rlActiveTextureSlot                = dwrap1('rlActiveTextureSlot');
    rlEnableTexture                    = dwrap1('rlEnableTexture');
    rlDisableTexture                   = dwrap0('rlDisableTexture');
    rlEnableTextureCubemap             = dwrap1('rlEnableTextureCubemap');
    rlDisableTextureCubemap            = dwrap0('rlDisableTextureCubemap');
    rlTextureParameters                = dwrap3('rlTextureParameters');
    rlCubemapParameters                = dwrap3('rlCubemapParameters');
    rlEnableShader                     = dwrap1('rlEnableShader');
    rlDisableShader                    = dwrap0('rlDisableShader');
    rlEnableFramebuffer                = dwrap1('rlEnableFramebuffer');
    rlDisableFramebuffer               = dwrap0('rlDisableFramebuffer');
    rlGetActiveFramebuffer             = dwrap0('rlGetActiveFramebuffer');
    rlActiveDrawBuffers                = dwrap1('rlActiveDrawBuffers');
    rlBlitFramebuffer                  = dwrap9('rlBlitFramebuffer');
    rlBindFramebuffer                  = dwrap2('rlBindFramebuffer');
    rlEnableColorBlend                 = dwrap0('rlEnableColorBlend');
    rlDisableColorBlend                = dwrap0('rlDisableColorBlend');
    rlEnableDepthTest                  = dwrap0('rlEnableDepthTest');
    rlDisableDepthTest                 = dwrap0('rlDisableDepthTest');
    rlEnableDepthMask                  = dwrap0('rlEnableDepthMask');
    rlDisableDepthMask                 = dwrap0('rlDisableDepthMask');
    rlEnableBackfaceCulling            = dwrap0('rlEnableBackfaceCulling');
    rlDisableBackfaceCulling           = dwrap0('rlDisableBackfaceCulling');
    rlColorMask                        = dwrap4('rlColorMask');
    rlSetCullFace                      = dwrap1('rlSetCullFace');
    rlEnableScissorTest                = dwrap0('rlEnableScissorTest');
    rlDisableScissorTest               = dwrap0('rlDisableScissorTest');
    rlScissor                          = dwrap4('rlScissor');
    rlEnablePointMode                  = dwrap0('rlEnablePointMode');
    rlDisablePointMode                 = dwrap0('rlDisablePointMode');
    rlSetPointSize                     = dwrap1('rlSetPointSize');
    rlGetPointSize                     = dwrap0('rlGetPointSize');
    rlEnableWireMode                   = dwrap0('rlEnableWireMode');
    rlDisableWireMode                  = dwrap0('rlDisableWireMode');
    rlSetLineWidth                     = dwrap1('rlSetLineWidth');
    rlGetLineWidth                     = dwrap0('rlGetLineWidth');
    rlEnableSmoothLines                = dwrap0('rlEnableSmoothLines');
    rlDisableSmoothLines               = dwrap0('rlDisableSmoothLines');
    rlEnableStereoRender               = dwrap0('rlEnableStereoRender');
    rlDisableStereoRender              = dwrap0('rlDisableStereoRender');
    rlIsStereoRenderEnabled            = dwrap0('rlIsStereoRenderEnabled');
    rlClearColor                       = dwrap4('rlClearColor');
    rlClearScreenBuffers               = dwrap0('rlClearScreenBuffers');
    rlCheckErrors                      = dwrap0('rlCheckErrors');
    rlSetBlendMode                     = dwrap1('rlSetBlendMode');
    rlSetBlendFactors                  = dwrap3('rlSetBlendFactors');
    rlSetBlendFactorsSeparate          = dwrap6('rlSetBlendFactorsSeparate');
    rlglInit                           = dwrap2('rlglInit');
    rlglClose                          = dwrap0('rlglClose');
    rlLoadExtensions                   = dwrap1('rlLoadExtensions');
    rlGetProcAddress                   = pwrap1('rlGetProcAddress');
    rlGetVersion                       = dwrap0('rlGetVersion');
    rlSetFramebufferWidth              = dwrap1('rlSetFramebufferWidth');
    rlGetFramebufferWidth              = dwrap0('rlGetFramebufferWidth');
    rlSetFramebufferHeight             = dwrap1('rlSetFramebufferHeight');
    rlGetFramebufferHeight             = dwrap0('rlGetFramebufferHeight');
    rlGetTextureIdDefault              = dwrap0('rlGetTextureIdDefault');
    rlGetShaderIdDefault               = dwrap0('rlGetShaderIdDefault');
    rlGetShaderLocsDefault             = pwrap0('rlGetShaderLocsDefault');
    rlLoadRenderBatch                  = swrap2('rlLoadRenderBatch');
    rlUnloadRenderBatch                = dwrap1('rlUnloadRenderBatch');
    rlDrawRenderBatch                  = dwrap1('rlDrawRenderBatch');
    rlSetRenderBatchActive             = dwrap1('rlSetRenderBatchActive');
    rlDrawRenderBatchActive            = dwrap0('rlDrawRenderBatchActive');
    rlCheckRenderBatchLimit            = dwrap1('rlCheckRenderBatchLimit');
    rlSetTexture                       = dwrap1('rlSetTexture');
    rlLoadVertexArray                  = dwrap0('rlLoadVertexArray');
    rlLoadVertexBuffer                 = dwrap3('rlLoadVertexBuffer');
    rlLoadVertexBufferElement          = dwrap3('rlLoadVertexBufferElement');
    rlUpdateVertexBuffer               = dwrap4('rlUpdateVertexBuffer');
    rlUpdateVertexBufferElements       = dwrap4('rlUpdateVertexBufferElements');
    rlUnloadVertexArray                = dwrap1('rlUnloadVertexArray');
    rlUnloadVertexBuffer               = dwrap1('rlUnloadVertexBuffer');
    rlSetVertexAttribute               = dwrap6('rlSetVertexAttribute');
    rlSetVertexAttributeDivisor        = dwrap2('rlSetVertexAttributeDivisor');
    rlSetVertexAttributeDefault        = dwrap4('rlSetVertexAttributeDefault');
    rlDrawVertexArray                  = dwrap2('rlDrawVertexArray');
    rlDrawVertexArrayElements          = dwrap3('rlDrawVertexArrayElements');
    rlDrawVertexArrayInstanced         = dwrap3('rlDrawVertexArrayInstanced');
    rlDrawVertexArrayElementsInstanced = dwrap4('rlDrawVertexArrayElementsInstanced');
    rlLoadTexture                      = dwrap5('rlLoadTexture');
    rlLoadTextureDepth                 = dwrap3('rlLoadTextureDepth');
    rlLoadTextureCubemap               = dwrap4('rlLoadTextureCubemap');
    rlUpdateTexture                    = dwrap7('rlUpdateTexture');
    rlGetGlTextureFormats              = dwrap4('rlGetGlTextureFormats');
    rlGetPixelFormatName               = pwrap1('rlGetPixelFormatName');
    rlUnloadTexture                    = dwrap1('rlUnloadTexture');
    rlGenTextureMipmaps                = dwrap5('rlGenTextureMipmaps');
    rlReadTexturePixels                = pwrap4('rlReadTexturePixels');
    rlReadScreenPixels                 = pwrap2('rlReadScreenPixels');
    rlLoadFramebuffer                  = dwrap0('rlLoadFramebuffer');
    rlFramebufferAttach                = dwrap5('rlFramebufferAttach');
    rlFramebufferComplete              = dwrap1('rlFramebufferComplete');
    rlUnloadFramebuffer                = dwrap1('rlUnloadFramebuffer');
    rlCopyFramebuffer                  = dwrap6('rlCopyFramebuffer');
    rlResizeFramebuffer                = dwrap2('rlResizeFramebuffer');
    rlLoadShader                       = dwrap2('rlLoadShader');
    rlLoadShaderProgram                = dwrap2('rlLoadShaderProgram');
    rlLoadShaderProgramEx              = dwrap2('rlLoadShaderProgramEx');
    rlLoadShaderProgramCompute         = dwrap1('rlLoadShaderProgramCompute');
    rlUnloadShader                     = dwrap1('rlUnloadShader');
    rlUnloadShaderProgram              = dwrap1('rlUnloadShaderProgram');
    rlGetLocationUniform               = dwrap2('rlGetLocationUniform');
    rlGetLocationAttrib                = dwrap2('rlGetLocationAttrib');
    rlSetUniform                       = dwrap4('rlSetUniform');
    rlSetUniformMatrix                 = dwrap2('rlSetUniformMatrix');
    rlSetUniformMatrices               = dwrap3('rlSetUniformMatrices');
    rlSetUniformSampler                = dwrap2('rlSetUniformSampler');
    rlSetShader                        = dwrap2('rlSetShader');
    rlComputeShaderDispatch            = dwrap3('rlComputeShaderDispatch');
    rlLoadShaderBuffer                 = dwrap3('rlLoadShaderBuffer');
    rlUnloadShaderBuffer               = dwrap1('rlUnloadShaderBuffer');
    rlUpdateShaderBuffer               = dwrap4('rlUpdateShaderBuffer');
    rlBindShaderBuffer                 = dwrap2('rlBindShaderBuffer');
    rlReadShaderBuffer                 = dwrap4('rlReadShaderBuffer');
    rlCopyShaderBuffer                 = dwrap5('rlCopyShaderBuffer');
    rlGetShaderBufferSize              = dwrap1('rlGetShaderBufferSize');
    rlBindImageTexture                 = dwrap4('rlBindImageTexture');
    rlGetMatrixModelview               = swrap0('rlGetMatrixModelview');
    rlGetMatrixProjection              = swrap0('rlGetMatrixProjection');
    rlGetMatrixTransform               = swrap0('rlGetMatrixTransform');
    rlGetMatrixProjectionStereo        = swrap1('rlGetMatrixProjectionStereo');
    rlGetMatrixViewOffsetStereo        = swrap1('rlGetMatrixViewOffsetStereo');
    rlSetMatrixProjection              = dwrap1('rlSetMatrixProjection');
    rlSetMatrixModelview               = dwrap1('rlSetMatrixModelview');
    rlSetMatrixProjectionStereo        = dwrap2('rlSetMatrixProjectionStereo');
    rlSetMatrixViewOffsetStereo        = dwrap2('rlSetMatrixViewOffsetStereo');
    rlLoadDrawCube                     = dwrap0('rlLoadDrawCube');
    rlLoadDrawQuad                     = dwrap0('rlLoadDrawQuad');
  }
}