part of '../../../raylib_dartified_web.dart';

class RaylibRlgl extends RaylibModuleWasm with RaylibRlglModuleExtras<Raylib> {
  /// Choose the current matrix to be transformed
  late final JSFunction rlMatrixMode;
  /// Push the current matrix to stack
  late final JSFunction rlPushMatrix;
  /// Pop latest inserted matrix from stack
  late final JSFunction rlPopMatrix;
  /// Reset current matrix to identity matrix
  late final JSFunction rlLoadIdentity;
  /// Multiply the current matrix by a translation matrix
  late final JSFunction rlTranslatef;
  /// Multiply the current matrix by a rotation matrix
  late final JSFunction rlRotatef;
  /// Multiply the current matrix by a scaling matrix
  late final JSFunction rlScalef;
  /// Multiply the current matrix by another matrix
  late final JSFunction rlMultMatrixf;
  /// Multiply the current matrix by a perspective matrix generated by parameters
  late final JSFunction rlFrustum;
  /// Multiply the current matrix by an orthographic matrix generated by parameters
  late final JSFunction rlOrtho;
  /// Set the viewport area
  late final JSFunction rlViewport;
  /// Set clip planes distances
  late final JSFunction rlSetClipPlanes;
  /// Get cull plane distance near
  late final JSFunction rlGetCullDistanceNear;
  /// Get cull plane distance far
  late final JSFunction rlGetCullDistanceFar;
  /// Initialize drawing mode (how to organize vertex)
  late final JSFunction rlBegin;
  /// Finish vertex providing
  late final JSFunction rlEnd;
  /// Define one vertex (position) - 2 int
  late final JSFunction rlVertex2i;
  /// Define one vertex (position) - 2 float
  late final JSFunction rlVertex2f;
  /// Define one vertex (position) - 3 float
  late final JSFunction rlVertex3f;
  /// Define one vertex (texture coordinate) - 2 float
  late final JSFunction rlTexCoord2f;
  /// Define one vertex (normal) - 3 float
  late final JSFunction rlNormal3f;
  /// Define one vertex (color) - 4 byte
  late final JSFunction rlColor4ub;
  /// Define one vertex (color) - 3 float
  late final JSFunction rlColor3f;
  /// Define one vertex (color) - 4 float
  late final JSFunction rlColor4f;
  /// Enable vertex array (VAO, if supported)
  late final JSFunction rlEnableVertexArray;
  /// Disable vertex array (VAO, if supported)
  late final JSFunction rlDisableVertexArray;
  /// Enable vertex buffer (VBO)
  late final JSFunction rlEnableVertexBuffer;
  /// Disable vertex buffer (VBO)
  late final JSFunction rlDisableVertexBuffer;
  /// Enable vertex buffer element (VBO element)
  late final JSFunction rlEnableVertexBufferElement;
  /// Disable vertex buffer element (VBO element)
  late final JSFunction rlDisableVertexBufferElement;
  /// Enable vertex attribute index
  late final JSFunction rlEnableVertexAttribute;
  /// Disable vertex attribute index
  late final JSFunction rlDisableVertexAttribute;
  /// Enable attribute state pointer
  late final JSFunction rlEnableStatePointer;
  /// Disable attribute state pointer
  late final JSFunction rlDisableStatePointer;
  /// Select and active a texture slot
  late final JSFunction rlActiveTextureSlot;
  /// Enable texture
  late final JSFunction rlEnableTexture;
  /// Disable texture
  late final JSFunction rlDisableTexture;
  /// Enable texture cubemap
  late final JSFunction rlEnableTextureCubemap;
  /// Disable texture cubemap
  late final JSFunction rlDisableTextureCubemap;
  /// Set texture parameters (filter, wrap)
  late final JSFunction rlTextureParameters;
  /// Set cubemap parameters (filter, wrap)
  late final JSFunction rlCubemapParameters;
  /// Enable shader program
  late final JSFunction rlEnableShader;
  /// Disable shader program
  late final JSFunction rlDisableShader;
  /// Enable render texture (fbo)
  late final JSFunction rlEnableFramebuffer;
  /// Disable render texture (fbo), return to default framebuffer
  late final JSFunction rlDisableFramebuffer;
  /// Get the currently active render texture (fbo), 0 for default framebuffer
  late final JSFunction rlGetActiveFramebuffer;
  /// Activate multiple draw color buffers
  late final JSFunction rlActiveDrawBuffers;
  /// Blit active framebuffer to main framebuffer
  late final JSFunction rlBlitFramebuffer;
  /// Bind framebuffer (FBO)
  late final JSFunction rlBindFramebuffer;
  /// Enable color blending
  late final JSFunction rlEnableColorBlend;
  /// Disable color blending
  late final JSFunction rlDisableColorBlend;
  /// Enable depth test
  late final JSFunction rlEnableDepthTest;
  /// Disable depth test
  late final JSFunction rlDisableDepthTest;
  /// Enable depth write
  late final JSFunction rlEnableDepthMask;
  /// Disable depth write
  late final JSFunction rlDisableDepthMask;
  /// Enable backface culling
  late final JSFunction rlEnableBackfaceCulling;
  /// Disable backface culling
  late final JSFunction rlDisableBackfaceCulling;
  /// Color mask control
  late final JSFunction rlColorMask;
  /// Set face culling mode
  late final JSFunction rlSetCullFace;
  /// Enable scissor test
  late final JSFunction rlEnableScissorTest;
  /// Disable scissor test
  late final JSFunction rlDisableScissorTest;
  /// Scissor test
  late final JSFunction rlScissor;
  /// Enable point mode
  late final JSFunction rlEnablePointMode;
  /// Disable point mode
  late final JSFunction rlDisablePointMode;
  /// Set the point drawing size
  late final JSFunction rlSetPointSize;
  /// Get the point drawing size
  late final JSFunction rlGetPointSize;
  /// Enable wire mode
  late final JSFunction rlEnableWireMode;
  /// Disable wire mode
  late final JSFunction rlDisableWireMode;
  /// Set the line drawing width
  late final JSFunction rlSetLineWidth;
  /// Get the line drawing width
  late final JSFunction rlGetLineWidth;
  /// Enable line aliasing
  late final JSFunction rlEnableSmoothLines;
  /// Disable line aliasing
  late final JSFunction rlDisableSmoothLines;
  /// Enable stereo rendering
  late final JSFunction rlEnableStereoRender;
  /// Disable stereo rendering
  late final JSFunction rlDisableStereoRender;
  /// Check if stereo render is enabled
  late final JSFunction rlIsStereoRenderEnabled;
  /// Clear color buffer with color
  late final JSFunction rlClearColor;
  /// Clear used screen buffers (color and depth)
  late final JSFunction rlClearScreenBuffers;
  /// Check and log OpenGL error codes
  late final JSFunction rlCheckErrors;
  /// Set blending mode
  late final JSFunction rlSetBlendMode;
  /// Set blending mode factor and equation (using OpenGL factors)
  late final JSFunction rlSetBlendFactors;
  /// Set blending mode factors and equations separately (using OpenGL factors)
  late final JSFunction rlSetBlendFactorsSeparate;
  /// Initialize rlgl (buffers, shaders, textures, states)
  late final JSFunction rlglInit;
  /// De-initialize rlgl (buffers, shaders, textures)
  late final JSFunction rlglClose;
  /// Load OpenGL extensions (loader function required)
  late final JSFunction rlLoadExtensions;
  /// Get OpenGL procedure address
  late final JSFunction rlGetProcAddress;
  /// Get current OpenGL version
  late final JSFunction rlGetVersion;
  /// Set current framebuffer width
  late final JSFunction rlSetFramebufferWidth;
  /// Get default framebuffer width
  late final JSFunction rlGetFramebufferWidth;
  /// Set current framebuffer height
  late final JSFunction rlSetFramebufferHeight;
  /// Get default framebuffer height
  late final JSFunction rlGetFramebufferHeight;
  /// Get default texture id
  late final JSFunction rlGetTextureIdDefault;
  /// Get default shader id
  late final JSFunction rlGetShaderIdDefault;
  /// Get default shader locations
  late final JSFunction rlGetShaderLocsDefault;
  /// Load a render batch system
  late final JSFunction rlLoadRenderBatch;
  /// Unload render batch system
  late final JSFunction rlUnloadRenderBatch;
  /// Draw render batch data (Update->Draw->Reset)
  late final JSFunction rlDrawRenderBatch;
  /// Set the active render batch for rlgl (NULL for default internal)
  late final JSFunction rlSetRenderBatchActive;
  /// Update and draw internal render batch
  late final JSFunction rlDrawRenderBatchActive;
  /// Check internal buffer overflow for a given number of vertex
  late final JSFunction rlCheckRenderBatchLimit;
  /// Set current texture for render batch and check buffers limits
  late final JSFunction rlSetTexture;
  /// Load vertex array (vao) if supported
  late final JSFunction rlLoadVertexArray;
  /// Load a vertex buffer object
  late final JSFunction rlLoadVertexBuffer;
  /// Load vertex buffer elements object
  late final JSFunction rlLoadVertexBufferElement;
  /// Update vertex buffer object data on GPU buffer
  late final JSFunction rlUpdateVertexBuffer;
  /// Update vertex buffer elements data on GPU buffer
  late final JSFunction rlUpdateVertexBufferElements;
  /// Unload vertex array (vao)
  late final JSFunction rlUnloadVertexArray;
  /// Unload vertex buffer object
  late final JSFunction rlUnloadVertexBuffer;
  /// Set vertex attribute data configuration
  late final JSFunction rlSetVertexAttribute;
  /// Set vertex attribute data divisor
  late final JSFunction rlSetVertexAttributeDivisor;
  /// Set vertex attribute default value, when attribute to provided
  late final JSFunction rlSetVertexAttributeDefault;
  /// Draw vertex array (currently active vao)
  late final JSFunction rlDrawVertexArray;
  /// Draw vertex array elements
  late final JSFunction rlDrawVertexArrayElements;
  /// Draw vertex array (currently active vao) with instancing
  late final JSFunction rlDrawVertexArrayInstanced;
  /// Draw vertex array elements with instancing
  late final JSFunction rlDrawVertexArrayElementsInstanced;
  /// Load texture data
  late final JSFunction rlLoadTexture;
  /// Load depth texture/renderbuffer (to be attached to fbo)
  late final JSFunction rlLoadTextureDepth;
  /// Load texture cubemap data
  late final JSFunction rlLoadTextureCubemap;
  /// Update texture with new data on GPU
  late final JSFunction rlUpdateTexture;
  /// Get OpenGL internal formats
  late final JSFunction rlGetGlTextureFormats;
  /// Get name string for pixel format
  late final JSFunction rlGetPixelFormatName;
  /// Unload texture from GPU memory
  late final JSFunction rlUnloadTexture;
  /// Generate mipmap data for selected texture
  late final JSFunction rlGenTextureMipmaps;
  /// Read texture pixel data
  late final JSFunction rlReadTexturePixels;
  /// Read screen pixel data (color buffer)
  late final JSFunction rlReadScreenPixels;
  /// Load an empty framebuffer
  late final JSFunction rlLoadFramebuffer;
  /// Attach texture/renderbuffer to a framebuffer
  late final JSFunction rlFramebufferAttach;
  /// Verify framebuffer is complete
  late final JSFunction rlFramebufferComplete;
  /// Delete framebuffer from GPU
  late final JSFunction rlUnloadFramebuffer;
  /// Copy framebuffer pixel data to internal buffer
  late final JSFunction rlCopyFramebuffer;
  /// Resize internal framebuffer
  late final JSFunction rlResizeFramebuffer;
  /// Load (compile) shader and return shader id
  late final JSFunction rlLoadShader;
  /// Load shader from code strings
  late final JSFunction rlLoadShaderProgram;
  /// Load shader program, using already loaded shader ids
  late final JSFunction rlLoadShaderProgramEx;
  /// Load compute shader program
  late final JSFunction rlLoadShaderProgramCompute;
  /// Unload shader, loaded with rlLoadShader();
  late final JSFunction rlUnloadShader;
  /// Unload shader program
  late final JSFunction rlUnloadShaderProgram;
  /// Get shader location uniform, requires shader program id
  late final JSFunction rlGetLocationUniform;
  /// Get shader location attribute, requires shader program id
  late final JSFunction rlGetLocationAttrib;
  /// Set shader value uniform
  late final JSFunction rlSetUniform;
  /// Set shader value matrix
  late final JSFunction rlSetUniformMatrix;
  /// Set shader value matrices
  late final JSFunction rlSetUniformMatrices;
  /// Set shader value sampler
  late final JSFunction rlSetUniformSampler;
  /// Set shader currently active (id and locations)
  late final JSFunction rlSetShader;
  /// Dispatch compute shader (equivalent to *draw* for graphics pipeline)
  late final JSFunction rlComputeShaderDispatch;
  /// Load shader storage buffer object (SSBO)
  late final JSFunction rlLoadShaderBuffer;
  /// Unload shader storage buffer object (SSBO)
  late final JSFunction rlUnloadShaderBuffer;
  /// Update SSBO buffer data
  late final JSFunction rlUpdateShaderBuffer;
  /// Bind SSBO buffer
  late final JSFunction rlBindShaderBuffer;
  /// Read SSBO buffer data (GPU->CPU)
  late final JSFunction rlReadShaderBuffer;
  /// Copy SSBO data between buffers
  late final JSFunction rlCopyShaderBuffer;
  /// Get SSBO buffer size
  late final JSFunction rlGetShaderBufferSize;
  /// Bind image texture
  late final JSFunction rlBindImageTexture;
  /// Get internal modelview matrix
  late final JSFunction rlGetMatrixModelview;
  /// Get internal projection matrix
  late final JSFunction rlGetMatrixProjection;
  /// Get internal accumulated transform matrix
  late final JSFunction rlGetMatrixTransform;
  /// Get internal projection matrix for stereo render (selected eye)
  late final JSFunction rlGetMatrixProjectionStereo;
  /// Get internal view offset matrix for stereo render (selected eye)
  late final JSFunction rlGetMatrixViewOffsetStereo;
  /// Set a custom projection matrix (replaces internal projection matrix)
  late final JSFunction rlSetMatrixProjection;
  /// Set a custom modelview matrix (replaces internal modelview matrix)
  late final JSFunction rlSetMatrixModelview;
  /// Set eyes projection matrices for stereo rendering
  late final JSFunction rlSetMatrixProjectionStereo;
  /// Set eyes view offsets matrices for stereo rendering
  late final JSFunction rlSetMatrixViewOffsetStereo;
  /// Load and draw a cube
  late final JSFunction rlLoadDrawCube;
  /// Load and draw a quad
  late final JSFunction rlLoadDrawQuad;

  RaylibRlgl(super.rl) {
    rlMatrixMode                       = _module.dwrap('rlMatrixMode',                       n1, rv);
    rlPushMatrix                       = _module.dwrap('rlPushMatrix',                       n0, rv);
    rlPopMatrix                        = _module.dwrap('rlPopMatrix',                        n0, rv);
    rlLoadIdentity                     = _module.dwrap('rlLoadIdentity',                     n0, rv);
    rlTranslatef                       = _module.dwrap('rlTranslatef',                       n3, rv);
    rlRotatef                          = _module.dwrap('rlRotatef',                          n4, rv);
    rlScalef                           = _module.dwrap('rlScalef',                           n3, rv);
    rlMultMatrixf                      = _module.dwrap('rlMultMatrixf',                      n1, rv);
    rlFrustum                          = _module.dwrap('rlFrustum',                          n6, rv);
    rlOrtho                            = _module.dwrap('rlOrtho',                            n6, rv);
    rlViewport                         = _module.dwrap('rlViewport',                         n4, rv);
    rlSetClipPlanes                    = _module.dwrap('rlSetClipPlanes',                    n2, rv);
    rlGetCullDistanceNear              = _module.dwrap('rlGetCullDistanceNear',              n0, rn);
    rlGetCullDistanceFar               = _module.dwrap('rlGetCullDistanceFar',               n0, rn);
    rlBegin                            = _module.dwrap('rlBegin',                            n1, rv);
    rlEnd                              = _module.dwrap('rlEnd',                              n0, rv);
    rlVertex2i                         = _module.dwrap('rlVertex2i',                         n2, rv);
    rlVertex2f                         = _module.dwrap('rlVertex2f',                         n2, rv);
    rlVertex3f                         = _module.dwrap('rlVertex3f',                         n3, rv);
    rlTexCoord2f                       = _module.dwrap('rlTexCoord2f',                       n2, rv);
    rlNormal3f                         = _module.dwrap('rlNormal3f',                         n3, rv);
    rlColor4ub                         = _module.dwrap('rlColor4ub',                         n4, rv);
    rlColor3f                          = _module.dwrap('rlColor3f',                          n3, rv);
    rlColor4f                          = _module.dwrap('rlColor4f',                          n4, rv);
    rlEnableVertexArray                = _module.dwrap('rlEnableVertexArray',                n1, rn);
    rlDisableVertexArray               = _module.dwrap('rlDisableVertexArray',               n0, rv);
    rlEnableVertexBuffer               = _module.dwrap('rlEnableVertexBuffer',               n1, rv);
    rlDisableVertexBuffer              = _module.dwrap('rlDisableVertexBuffer',              n0, rv);
    rlEnableVertexBufferElement        = _module.dwrap('rlEnableVertexBufferElement',        n1, rv);
    rlDisableVertexBufferElement       = _module.dwrap('rlDisableVertexBufferElement',       n0, rv);
    rlEnableVertexAttribute            = _module.dwrap('rlEnableVertexAttribute',            n1, rv);
    rlDisableVertexAttribute           = _module.dwrap('rlDisableVertexAttribute',           n1, rv);
    rlEnableStatePointer               = _module.dwrap('rlEnableStatePointer',               n2, rv);
    rlDisableStatePointer              = _module.dwrap('rlDisableStatePointer',              n1, rv);
    rlActiveTextureSlot                = _module.dwrap('rlActiveTextureSlot',                n1, rv);
    rlEnableTexture                    = _module.dwrap('rlEnableTexture',                    n1, rv);
    rlDisableTexture                   = _module.dwrap('rlDisableTexture',                   n0, rv);
    rlEnableTextureCubemap             = _module.dwrap('rlEnableTextureCubemap',             n1, rv);
    rlDisableTextureCubemap            = _module.dwrap('rlDisableTextureCubemap',            n0, rv);
    rlTextureParameters                = _module.dwrap('rlTextureParameters',                n3, rv);
    rlCubemapParameters                = _module.dwrap('rlCubemapParameters',                n3, rv);
    rlEnableShader                     = _module.dwrap('rlEnableShader',                     n1, rv);
    rlDisableShader                    = _module.dwrap('rlDisableShader',                    n0, rv);
    rlEnableFramebuffer                = _module.dwrap('rlEnableFramebuffer',                n1, rv);
    rlDisableFramebuffer               = _module.dwrap('rlDisableFramebuffer',               n0, rv);
    rlGetActiveFramebuffer             = _module.dwrap('rlGetActiveFramebuffer',             n0, rn);
    rlActiveDrawBuffers                = _module.dwrap('rlActiveDrawBuffers',                n1, rv);
    rlBlitFramebuffer                  = _module.dwrap('rlBlitFramebuffer',                  n9, rv);
    rlBindFramebuffer                  = _module.dwrap('rlBindFramebuffer',                  n2, rv);
    rlEnableColorBlend                 = _module.dwrap('rlEnableColorBlend',                 n0, rv);
    rlDisableColorBlend                = _module.dwrap('rlDisableColorBlend',                n0, rv);
    rlEnableDepthTest                  = _module.dwrap('rlEnableDepthTest',                  n0, rv);
    rlDisableDepthTest                 = _module.dwrap('rlDisableDepthTest',                 n0, rv);
    rlEnableDepthMask                  = _module.dwrap('rlEnableDepthMask',                  n0, rv);
    rlDisableDepthMask                 = _module.dwrap('rlDisableDepthMask',                 n0, rv);
    rlEnableBackfaceCulling            = _module.dwrap('rlEnableBackfaceCulling',            n0, rv);
    rlDisableBackfaceCulling           = _module.dwrap('rlDisableBackfaceCulling',           n0, rv);
    rlColorMask                        = _module.dwrap('rlColorMask',                        n4, rv);
    rlSetCullFace                      = _module.dwrap('rlSetCullFace',                      n1, rv);
    rlEnableScissorTest                = _module.dwrap('rlEnableScissorTest',                n0, rv);
    rlDisableScissorTest               = _module.dwrap('rlDisableScissorTest',               n0, rv);
    rlScissor                          = _module.dwrap('rlScissor',                          n4, rv);
    rlEnablePointMode                  = _module.dwrap('rlEnablePointMode',                  n0, rv);
    rlDisablePointMode                 = _module.dwrap('rlDisablePointMode',                 n0, rv);
    rlSetPointSize                     = _module.dwrap('rlSetPointSize',                     n1, rv);
    rlGetPointSize                     = _module.dwrap('rlGetPointSize',                     n0, rn);
    rlEnableWireMode                   = _module.dwrap('rlEnableWireMode',                   n0, rv);
    rlDisableWireMode                  = _module.dwrap('rlDisableWireMode',                  n0, rv);
    rlSetLineWidth                     = _module.dwrap('rlSetLineWidth',                     n1, rv);
    rlGetLineWidth                     = _module.dwrap('rlGetLineWidth',                     n0, rn);
    rlEnableSmoothLines                = _module.dwrap('rlEnableSmoothLines',                n0, rv);
    rlDisableSmoothLines               = _module.dwrap('rlDisableSmoothLines',               n0, rv);
    rlEnableStereoRender               = _module.dwrap('rlEnableStereoRender',               n0, rv);
    rlDisableStereoRender              = _module.dwrap('rlDisableStereoRender',              n0, rv);
    rlIsStereoRenderEnabled            = _module.dwrap('rlIsStereoRenderEnabled',            n0, rn);
    rlClearColor                       = _module.dwrap('rlClearColor',                       n4, rv);
    rlClearScreenBuffers               = _module.dwrap('rlClearScreenBuffers',               n0, rv);
    rlCheckErrors                      = _module.dwrap('rlCheckErrors',                      n0, rv);
    rlSetBlendMode                     = _module.dwrap('rlSetBlendMode',                     n1, rv);
    rlSetBlendFactors                  = _module.dwrap('rlSetBlendFactors',                  n3, rv);
    rlSetBlendFactorsSeparate          = _module.dwrap('rlSetBlendFactorsSeparate',          n6, rv);
    rlglInit                           = _module.dwrap('rlglInit',                           n2, rv);
    rlglClose                          = _module.dwrap('rlglClose',                          n0, rv);
    rlLoadExtensions                   = _module.dwrap('rlLoadExtensions',                   n1, rv);
    rlGetProcAddress                   = _module.dwrap('rlGetProcAddress',                   n1, rn);
    rlGetVersion                       = _module.dwrap('rlGetVersion',                       n0, rn);
    rlSetFramebufferWidth              = _module.dwrap('rlSetFramebufferWidth',              n1, rv);
    rlGetFramebufferWidth              = _module.dwrap('rlGetFramebufferWidth',              n0, rn);
    rlSetFramebufferHeight             = _module.dwrap('rlSetFramebufferHeight',             n1, rv);
    rlGetFramebufferHeight             = _module.dwrap('rlGetFramebufferHeight',             n0, rn);
    rlGetTextureIdDefault              = _module.dwrap('rlGetTextureIdDefault',              n0, rn);
    rlGetShaderIdDefault               = _module.dwrap('rlGetShaderIdDefault',               n0, rn);
    rlGetShaderLocsDefault             = _module.dwrap('rlGetShaderLocsDefault',             n0, rn);
    rlLoadRenderBatch                  = _module.dwrap('rlLoadRenderBatch',                  n3, rv);
    rlUnloadRenderBatch                = _module.dwrap('rlUnloadRenderBatch',                n1, rv);
    rlDrawRenderBatch                  = _module.dwrap('rlDrawRenderBatch',                  n1, rv);
    rlSetRenderBatchActive             = _module.dwrap('rlSetRenderBatchActive',             n1, rv);
    rlDrawRenderBatchActive            = _module.dwrap('rlDrawRenderBatchActive',            n0, rv);
    rlCheckRenderBatchLimit            = _module.dwrap('rlCheckRenderBatchLimit',            n1, rn);
    rlSetTexture                       = _module.dwrap('rlSetTexture',                       n1, rv);
    rlLoadVertexArray                  = _module.dwrap('rlLoadVertexArray',                  n0, rn);
    rlLoadVertexBuffer                 = _module.dwrap('rlLoadVertexBuffer',                 n3, rn);
    rlLoadVertexBufferElement          = _module.dwrap('rlLoadVertexBufferElement',          n3, rn);
    rlUpdateVertexBuffer               = _module.dwrap('rlUpdateVertexBuffer',               n4, rv);
    rlUpdateVertexBufferElements       = _module.dwrap('rlUpdateVertexBufferElements',       n4, rv);
    rlUnloadVertexArray                = _module.dwrap('rlUnloadVertexArray',                n1, rv);
    rlUnloadVertexBuffer               = _module.dwrap('rlUnloadVertexBuffer',               n1, rv);
    rlSetVertexAttribute               = _module.dwrap('rlSetVertexAttribute',               n6, rv);
    rlSetVertexAttributeDivisor        = _module.dwrap('rlSetVertexAttributeDivisor',        n2, rv);
    rlSetVertexAttributeDefault        = _module.dwrap('rlSetVertexAttributeDefault',        n4, rv);
    rlDrawVertexArray                  = _module.dwrap('rlDrawVertexArray',                  n2, rv);
    rlDrawVertexArrayElements          = _module.dwrap('rlDrawVertexArrayElements',          n3, rv);
    rlDrawVertexArrayInstanced         = _module.dwrap('rlDrawVertexArrayInstanced',         n3, rv);
    rlDrawVertexArrayElementsInstanced = _module.dwrap('rlDrawVertexArrayElementsInstanced', n4, rv);
    rlLoadTexture                      = _module.dwrap('rlLoadTexture',                      n5, rn);
    rlLoadTextureDepth                 = _module.dwrap('rlLoadTextureDepth',                 n3, rn);
    rlLoadTextureCubemap               = _module.dwrap('rlLoadTextureCubemap',               n4, rn);
    rlUpdateTexture                    = _module.dwrap('rlUpdateTexture',                    n7, rv);
    rlGetGlTextureFormats              = _module.dwrap('rlGetGlTextureFormats',              n4, rv);
    rlGetPixelFormatName               = _module.dwrap('rlGetPixelFormatName',               n1, rn);
    rlUnloadTexture                    = _module.dwrap('rlUnloadTexture',                    n1, rv);
    rlGenTextureMipmaps                = _module.dwrap('rlGenTextureMipmaps',                n5, rv);
    rlReadTexturePixels                = _module.dwrap('rlReadTexturePixels',                n4, rn);
    rlReadScreenPixels                 = _module.dwrap('rlReadScreenPixels',                 n2, rn);
    rlLoadFramebuffer                  = _module.dwrap('rlLoadFramebuffer',                  n0, rn);
    rlFramebufferAttach                = _module.dwrap('rlFramebufferAttach',                n5, rv);
    rlFramebufferComplete              = _module.dwrap('rlFramebufferComplete',              n1, rn);
    rlUnloadFramebuffer                = _module.dwrap('rlUnloadFramebuffer',                n1, rv);
    rlCopyFramebuffer                  = _module.dwrap('rlCopyFramebuffer',                  n6, rv);
    rlResizeFramebuffer                = _module.dwrap('rlResizeFramebuffer',                n2, rv);
    rlLoadShader                       = _module.dwrap('rlLoadShader',                       n2, rn);
    rlLoadShaderProgram                = _module.dwrap('rlLoadShaderProgram',                n2, rn);
    rlLoadShaderProgramEx              = _module.dwrap('rlLoadShaderProgramEx',              n2, rn);
    rlLoadShaderProgramCompute         = _module.dwrap('rlLoadShaderProgramCompute',         n1, rn);
    rlUnloadShader                     = _module.dwrap('rlUnloadShader',                     n1, rv);
    rlUnloadShaderProgram              = _module.dwrap('rlUnloadShaderProgram',              n1, rv);
    rlGetLocationUniform               = _module.dwrap('rlGetLocationUniform',               n2, rn);
    rlGetLocationAttrib                = _module.dwrap('rlGetLocationAttrib',                n2, rn);
    rlSetUniform                       = _module.dwrap('rlSetUniform',                       n4, rv);
    rlSetUniformMatrix                 = _module.dwrap('rlSetUniformMatrix',                 n2, rv);
    rlSetUniformMatrices               = _module.dwrap('rlSetUniformMatrices',               n3, rv);
    rlSetUniformSampler                = _module.dwrap('rlSetUniformSampler',                n2, rv);
    rlSetShader                        = _module.dwrap('rlSetShader',                        n2, rv);
    rlComputeShaderDispatch            = _module.dwrap('rlComputeShaderDispatch',            n3, rv);
    rlLoadShaderBuffer                 = _module.dwrap('rlLoadShaderBuffer',                 n3, rn);
    rlUnloadShaderBuffer               = _module.dwrap('rlUnloadShaderBuffer',               n1, rv);
    rlUpdateShaderBuffer               = _module.dwrap('rlUpdateShaderBuffer',               n4, rv);
    rlBindShaderBuffer                 = _module.dwrap('rlBindShaderBuffer',                 n2, rv);
    rlReadShaderBuffer                 = _module.dwrap('rlReadShaderBuffer',                 n4, rv);
    rlCopyShaderBuffer                 = _module.dwrap('rlCopyShaderBuffer',                 n5, rv);
    rlGetShaderBufferSize              = _module.dwrap('rlGetShaderBufferSize',              n1, rn);
    rlBindImageTexture                 = _module.dwrap('rlBindImageTexture',                 n4, rv);
    rlGetMatrixModelview               = _module.dwrap('rlGetMatrixModelview',               n1, rv);
    rlGetMatrixProjection              = _module.dwrap('rlGetMatrixProjection',              n1, rv);
    rlGetMatrixTransform               = _module.dwrap('rlGetMatrixTransform',               n1, rv);
    rlGetMatrixProjectionStereo        = _module.dwrap('rlGetMatrixProjectionStereo',        n2, rv);
    rlGetMatrixViewOffsetStereo        = _module.dwrap('rlGetMatrixViewOffsetStereo',        n2, rv);
    rlSetMatrixProjection              = _module.dwrap('rlSetMatrixProjection',              n1, rv);
    rlSetMatrixModelview               = _module.dwrap('rlSetMatrixModelview',               n1, rv);
    rlSetMatrixProjectionStereo        = _module.dwrap('rlSetMatrixProjectionStereo',        n2, rv);
    rlSetMatrixViewOffsetStereo        = _module.dwrap('rlSetMatrixViewOffsetStereo',        n2, rv);
    rlLoadDrawCube                     = _module.dwrap('rlLoadDrawCube',                     n0, rv);
    rlLoadDrawQuad                     = _module.dwrap('rlLoadDrawQuad',                     n0, rv);
  }
}