part of '../../raylib_dartified_web.dart';

class RaylibCore extends RaylibModuleWasm {  
  late final JSFunction InitWindow;
  late final JSFunction CloseWindow;
  late final JSFunction WindowShouldClose;
  late final JSFunction IsWindowReady;
  late final JSFunction IsWindowFullscreen;
  late final JSFunction IsWindowHidden;
  late final JSFunction IsWindowMinimized;
  late final JSFunction IsWindowMaximized;
  late final JSFunction IsWindowFocused;
  late final JSFunction IsWindowResized;
  late final JSFunction IsWindowState;
  late final JSFunction SetWindowState;
  late final JSFunction ClearWindowState;
  late final JSFunction ToggleFullscreen;
  late final JSFunction ToggleBorderlessWindowed;
  late final JSFunction MaximizeWindow;
  late final JSFunction MinimizeWindow;
  late final JSFunction RestoreWindow;
  late final JSFunction SetWindowIcon;
  late final JSFunction SetWindowIcons;
  late final JSFunction SetWindowTitle;
  late final JSFunction SetWindowPosition;
  late final JSFunction SetWindowMonitor;
  late final JSFunction SetWindowMinSize;
  late final JSFunction SetWindowMaxSize;
  late final JSFunction SetWindowSize;
  late final JSFunction SetWindowOpacity;
  late final JSFunction SetWindowFocused;
  late final JSFunction GetWindowHandle;
  late final JSFunction GetScreenWidth;
  late final JSFunction GetScreenHeight;
  late final JSFunction GetRenderWidth;
  late final JSFunction GetRenderHeight;
  late final JSFunction GetMonitorCount;
  late final JSFunction GetCurrentMonitor;
  late final JSFunction GetMonitorPosition;
  late final JSFunction GetMonitorWidth;
  late final JSFunction GetMonitorHeight;
  late final JSFunction GetMonitorPhysicalWidth;
  late final JSFunction GetMonitorPhysicalHeight;
  late final JSFunction GetMonitorRefreshRate;
  late final JSFunction GetWindowPosition;
  late final JSFunction GetWindowScaleDPI;
  late final JSFunction GetMonitorName;
  late final JSFunction SetClipboardText;
  late final JSFunction GetClipboardText;
  late final JSFunction GetClipboardImage;
  late final JSFunction EnableEventWaiting;
  late final JSFunction DisableEventWaiting;
  late final JSFunction ShowCursor;
  late final JSFunction HideCursor;
  late final JSFunction IsCursorHidden;
  late final JSFunction EnableCursor;
  late final JSFunction DisableCursor;
  late final JSFunction IsCursorOnScreen;
  late final JSFunction ClearBackground;
  late final JSFunction BeginDrawing;
  late final JSFunction EndDrawing;
  late final JSFunction BeginMode2D;
  late final JSFunction EndMode2D;
  late final JSFunction BeginMode3D;
  late final JSFunction EndMode3D;
  late final JSFunction BeginTextureMode;
  late final JSFunction EndTextureMode;
  late final JSFunction BeginShaderMode;
  late final JSFunction EndShaderMode;
  late final JSFunction BeginBlendMode;
  late final JSFunction EndBlendMode;
  late final JSFunction BeginScissorMode;
  late final JSFunction EndScissorMode;
  late final JSFunction BeginVrStereoMode;
  late final JSFunction EndVrStereoMode;
  late final JSFunction LoadVrStereoConfig;
  late final JSFunction UnloadVrStereoConfig;
  late final JSFunction LoadShader;
  late final JSFunction LoadShaderFromMemory;
  late final JSFunction IsShaderValid;
  late final JSFunction GetShaderLocation;
  late final JSFunction GetShaderLocationAttrib;
  late final JSFunction SetShaderValue;
  late final JSFunction SetShaderValueV;
  late final JSFunction SetShaderValueMatrix;
  late final JSFunction SetShaderValueTexture;
  late final JSFunction UnloadShader;
  late final JSFunction GetScreenToWorldRay;
  late final JSFunction GetScreenToWorldRayEx;
  late final JSFunction GetWorldToScreen;
  late final JSFunction GetWorldToScreenEx;
  late final JSFunction GetWorldToScreen2D;
  late final JSFunction GetScreenToWorld2D;
  late final JSFunction GetCameraMatrix;
  late final JSFunction GetCameraMatrix2D;
  late final JSFunction SetTargetFPS;
  late final JSFunction GetFrameTime;
  late final JSFunction GetTime;
  late final JSFunction GetFPS;
  late final JSFunction SwapScreenBuffer;
  late final JSFunction PollInputEvents;
  late final JSFunction WaitTime;
  late final JSFunction SetRandomSeed;
  late final JSFunction GetRandomValue;
  late final JSFunction LoadRandomSequence;
  late final JSFunction UnloadRandomSequence;
  late final JSFunction TakeScreenshot;
  late final JSFunction SetConfigFlags;
  late final JSFunction OpenURL;
  late final JSFunction TraceLog;
  late final JSFunction SetTraceLogLevel;
  late final JSFunction SetLoadFileDataCallback;
  late final JSFunction SetSaveFileDataCallback;
  late final JSFunction SetLoadFileTextCallback;
  late final JSFunction SetSaveFileTextCallback;
  late final JSFunction LoadFileData;
  late final JSFunction UnloadFileData;
  late final JSFunction SaveFileData;
  late final JSFunction ExportDataAsCode;
  late final JSFunction LoadFileText;
  late final JSFunction UnloadFileText;
  late final JSFunction SaveFileText;
  late final JSFunction FileExists;
  late final JSFunction DirectoryExists;
  late final JSFunction IsFileExtension;
  late final JSFunction GetFileLength;
  late final JSFunction GetFileExtension;
  late final JSFunction GetFileName;
  late final JSFunction GetFileNameWithoutExt;
  late final JSFunction GetDirectoryPath;
  late final JSFunction GetPrevDirectoryPath;
  late final JSFunction GetWorkingDirectory;
  late final JSFunction GetApplicationDirectory;
  late final JSFunction MakeDirectory;
  late final JSFunction ChangeDirectory;
  late final JSFunction IsPathFile;
  late final JSFunction IsFileNameValid;
  late final JSFunction LoadDirectoryFiles;
  late final JSFunction LoadDirectoryFilesEx;
  late final JSFunction UnloadDirectoryFiles;
  late final JSFunction IsFileDropped;
  late final JSFunction LoadDroppedFiles;
  late final JSFunction UnloadDroppedFiles;
  late final JSFunction GetFileModTime;
  late final JSFunction CompressData;
  late final JSFunction DecompressData;
  late final JSFunction EncodeDataBase64;
  late final JSFunction DecodeDataBase64;
  late final JSFunction ComputeCRC32;
  late final JSFunction ComputeMD5;
  late final JSFunction ComputeSHA1;
  late final JSFunction LoadAutomationEventList;
  late final JSFunction UnloadAutomationEventList;
  late final JSFunction ExportAutomationEventList;
  late final JSFunction SetAutomationEventList;
  late final JSFunction SetAutomationEventBaseFrame;
  late final JSFunction StartAutomationEventRecording;
  late final JSFunction StopAutomationEventRecording;
  late final JSFunction PlayAutomationEvent;
  late final JSFunction IsKeyPressed;
  late final JSFunction IsKeyPressedRepeat;
  late final JSFunction IsKeyDown;
  late final JSFunction IsKeyReleased;
  late final JSFunction IsKeyUp;
  late final JSFunction GetKeyPressed;
  late final JSFunction GetCharPressed;
  late final JSFunction SetExitKey;
  late final JSFunction IsGamepadAvailable;
  late final JSFunction GetGamepadName;
  late final JSFunction IsGamepadButtonPressed;
  late final JSFunction IsGamepadButtonDown;
  late final JSFunction IsGamepadButtonReleased;
  late final JSFunction IsGamepadButtonUp;
  late final JSFunction GetGamepadButtonPressed;
  late final JSFunction GetGamepadAxisCount;
  late final JSFunction GetGamepadAxisMovement;
  late final JSFunction SetGamepadMappings;
  late final JSFunction SetGamepadVibration;
  late final JSFunction IsMouseButtonPressed;
  late final JSFunction IsMouseButtonDown;
  late final JSFunction IsMouseButtonReleased;
  late final JSFunction IsMouseButtonUp;
  late final JSFunction GetMouseX;
  late final JSFunction GetMouseY;
  late final JSFunction GetMousePosition;
  late final JSFunction GetMouseDelta;
  late final JSFunction SetMousePosition;
  late final JSFunction SetMouseOffset;
  late final JSFunction SetMouseScale;
  late final JSFunction GetMouseWheelMove;
  late final JSFunction GetMouseWheelMoveV;
  late final JSFunction SetMouseCursor;
  late final JSFunction GetTouchX;
  late final JSFunction GetTouchY;
  late final JSFunction GetTouchPosition;
  late final JSFunction GetTouchPointId;
  late final JSFunction GetTouchPointCount;
  late final JSFunction SetGesturesEnabled;
  late final JSFunction IsGestureDetected;
  late final JSFunction GetGestureDetected;
  late final JSFunction GetGestureHoldDuration;
  late final JSFunction GetGestureDragVector;
  late final JSFunction GetGestureDragAngle;
  late final JSFunction GetGesturePinchVector;
  late final JSFunction GetGesturePinchAngle;
  late final JSFunction UpdateCamera;
  late final JSFunction UpdateCameraPro;
  late final JSFunction SetShapesTexture;
  late final JSFunction GetShapesTexture;
  late final JSFunction GetShapesTextureRectangle;
  late final JSFunction DrawPixel;
  late final JSFunction DrawPixelV;
  late final JSFunction DrawLine;
  late final JSFunction DrawLineV;
  late final JSFunction DrawLineEx;
  late final JSFunction DrawLineStrip;
  late final JSFunction DrawLineBezier;
  late final JSFunction DrawCircle;
  late final JSFunction DrawCircleSector;
  late final JSFunction DrawCircleSectorLines;
  late final JSFunction DrawCircleGradient;
  late final JSFunction DrawCircleV;
  late final JSFunction DrawCircleLines;
  late final JSFunction DrawCircleLinesV;
  late final JSFunction DrawEllipse;
  late final JSFunction DrawEllipseLines;
  late final JSFunction DrawRing;
  late final JSFunction DrawRingLines;
  late final JSFunction DrawRectangle;
  late final JSFunction DrawRectangleV;
  late final JSFunction DrawRectangleRec;
  late final JSFunction DrawRectanglePro;
  late final JSFunction DrawRectangleGradientV;
  late final JSFunction DrawRectangleGradientH;
  late final JSFunction DrawRectangleGradientEx;
  late final JSFunction DrawRectangleLines;
  late final JSFunction DrawRectangleLinesEx;
  late final JSFunction DrawRectangleRounded;
  late final JSFunction DrawRectangleRoundedLines;
  late final JSFunction DrawRectangleRoundedLinesEx;
  late final JSFunction DrawTriangle;
  late final JSFunction DrawTriangleLines;
  late final JSFunction DrawTriangleFan;
  late final JSFunction DrawTriangleStrip;
  late final JSFunction DrawPoly;
  late final JSFunction DrawPolyLines;
  late final JSFunction DrawPolyLinesEx;
  late final JSFunction DrawSplineLinear;
  late final JSFunction DrawSplineBasis;
  late final JSFunction DrawSplineCatmullRom;
  late final JSFunction DrawSplineBezierQuadratic;
  late final JSFunction DrawSplineBezierCubic;
  late final JSFunction DrawSplineSegmentLinear;
  late final JSFunction DrawSplineSegmentBasis;
  late final JSFunction DrawSplineSegmentCatmullRom;
  late final JSFunction DrawSplineSegmentBezierQuadratic;
  late final JSFunction DrawSplineSegmentBezierCubic;
  late final JSFunction GetSplinePointLinear;
  late final JSFunction GetSplinePointBasis;
  late final JSFunction GetSplinePointCatmullRom;
  late final JSFunction GetSplinePointBezierQuad;
  late final JSFunction GetSplinePointBezierCubic;
  late final JSFunction CheckCollisionRecs;
  late final JSFunction CheckCollisionCircles;
  late final JSFunction CheckCollisionCircleRec;
  late final JSFunction CheckCollisionCircleLine;
  late final JSFunction CheckCollisionPointRec;
  late final JSFunction CheckCollisionPointCircle;
  late final JSFunction CheckCollisionPointTriangle;
  late final JSFunction CheckCollisionPointLine;
  late final JSFunction CheckCollisionPointPoly;
  late final JSFunction CheckCollisionLines;
  late final JSFunction GetCollisionRec;
  late final JSFunction LoadImage;
  late final JSFunction LoadImageRaw;
  late final JSFunction LoadImageAnim;
  late final JSFunction LoadImageAnimFromMemory;
  late final JSFunction LoadImageFromMemory;
  late final JSFunction LoadImageFromTexture;
  late final JSFunction LoadImageFromScreen;
  late final JSFunction IsImageValid;
  late final JSFunction UnloadImage;
  late final JSFunction ExportImage;
  late final JSFunction ExportImageToMemory;
  late final JSFunction ExportImageAsCode;
  late final JSFunction GenImageColor;
  late final JSFunction GenImageGradientLinear;
  late final JSFunction GenImageGradientRadial;
  late final JSFunction GenImageGradientSquare;
  late final JSFunction GenImageChecked;
  late final JSFunction GenImageWhiteNoise;
  late final JSFunction GenImagePerlinNoise;
  late final JSFunction GenImageCellular;
  late final JSFunction GenImageText;
  late final JSFunction ImageCopy;
  late final JSFunction ImageFromImage;
  late final JSFunction ImageFromChannel;
  late final JSFunction ImageText;
  late final JSFunction ImageTextEx;
  late final JSFunction ImageFormat;
  late final JSFunction ImageToPOT;
  late final JSFunction ImageCrop;
  late final JSFunction ImageAlphaCrop;
  late final JSFunction ImageAlphaClear;
  late final JSFunction ImageAlphaMask;
  late final JSFunction ImageAlphaPremultiply;
  late final JSFunction ImageBlurGaussian;
  late final JSFunction ImageKernelConvolution;
  late final JSFunction ImageResize;
  late final JSFunction ImageResizeNN;
  late final JSFunction ImageResizeCanvas;
  late final JSFunction ImageMipmaps;
  late final JSFunction ImageDither;
  late final JSFunction ImageFlipVertical;
  late final JSFunction ImageFlipHorizontal;
  late final JSFunction ImageRotate;
  late final JSFunction ImageRotateCW;
  late final JSFunction ImageRotateCCW;
  late final JSFunction ImageColorTint;
  late final JSFunction ImageColorInvert;
  late final JSFunction ImageColorGrayscale;
  late final JSFunction ImageColorContrast;
  late final JSFunction ImageColorBrightness;
  late final JSFunction ImageColorReplace;
  late final JSFunction LoadImageColors;
  late final JSFunction LoadImagePalette;
  late final JSFunction UnloadImageColors;
  late final JSFunction UnloadImagePalette;
  late final JSFunction GetImageAlphaBorder;
  late final JSFunction GetImageColor;
  late final JSFunction ImageClearBackground;
  late final JSFunction ImageDrawPixel;
  late final JSFunction ImageDrawPixelV;
  late final JSFunction ImageDrawLine;
  late final JSFunction ImageDrawLineV;
  late final JSFunction ImageDrawLineEx;
  late final JSFunction ImageDrawCircle;
  late final JSFunction ImageDrawCircleV;
  late final JSFunction ImageDrawCircleLines;
  late final JSFunction ImageDrawCircleLinesV;
  late final JSFunction ImageDrawRectangle;
  late final JSFunction ImageDrawRectangleV;
  late final JSFunction ImageDrawRectangleRec;
  late final JSFunction ImageDrawRectangleLines;
  late final JSFunction ImageDrawTriangle;
  late final JSFunction ImageDrawTriangleEx;
  late final JSFunction ImageDrawTriangleLines;
  late final JSFunction ImageDrawTriangleFan;
  late final JSFunction ImageDrawTriangleStrip;
  late final JSFunction ImageDraw;
  late final JSFunction ImageDrawText;
  late final JSFunction ImageDrawTextEx;
  late final JSFunction LoadTexture;
  late final JSFunction LoadTextureFromImage;
  late final JSFunction LoadTextureCubemap;
  late final JSFunction LoadRenderTexture;
  late final JSFunction IsTextureValid;
  late final JSFunction UnloadTexture;
  late final JSFunction IsRenderTextureValid;
  late final JSFunction UnloadRenderTexture;
  late final JSFunction UpdateTexture;
  late final JSFunction UpdateTextureRec;
  late final JSFunction GenTextureMipmaps;
  late final JSFunction SetTextureFilter;
  late final JSFunction SetTextureWrap;
  late final JSFunction DrawTexture;
  late final JSFunction DrawTextureV;
  late final JSFunction DrawTextureEx;
  late final JSFunction DrawTextureRec;
  late final JSFunction DrawTexturePro;
  late final JSFunction DrawTextureNPatch;
  late final JSFunction ColorIsEqual;
  late final JSFunction Fade;
  late final JSFunction ColorToInt;
  late final JSFunction ColorNormalize;
  late final JSFunction ColorFromNormalized;
  late final JSFunction ColorToHSV;
  late final JSFunction ColorFromHSV;
  late final JSFunction ColorTint;
  late final JSFunction ColorBrightness;
  late final JSFunction ColorContrast;
  late final JSFunction ColorAlpha;
  late final JSFunction ColorAlphaBlend;
  late final JSFunction ColorLerp;
  late final JSFunction GetColor;
  late final JSFunction GetPixelColor;
  late final JSFunction SetPixelColor;
  late final JSFunction GetPixelDataSize;
  late final JSFunction GetFontDefault;
  late final JSFunction LoadFont;
  late final JSFunction LoadFontEx;
  late final JSFunction LoadFontFromImage;
  late final JSFunction LoadFontFromMemory;
  late final JSFunction IsFontValid;
  late final JSFunction LoadFontData;
  late final JSFunction GenImageFontAtlas;
  late final JSFunction UnloadFontData;
  late final JSFunction UnloadFont;
  late final JSFunction ExportFontAsCode;
  late final JSFunction DrawFPS;
  late final JSFunction DrawText;
  late final JSFunction DrawTextEx;
  late final JSFunction DrawTextPro;
  late final JSFunction DrawTextCodepoint;
  late final JSFunction DrawTextCodepoints;
  late final JSFunction SetTextLineSpacing;
  late final JSFunction MeasureText;
  late final JSFunction MeasureTextEx;
  late final JSFunction GetGlyphIndex;
  late final JSFunction GetGlyphInfo;
  late final JSFunction GetGlyphAtlasRec;
  late final JSFunction LoadUTF8;
  late final JSFunction UnloadUTF8;
  late final JSFunction LoadCodepoints;
  late final JSFunction UnloadCodepoints;
  late final JSFunction GetCodepointCount;
  late final JSFunction GetCodepoint;
  late final JSFunction GetCodepointNext;
  late final JSFunction GetCodepointPrevious;
  late final JSFunction CodepointToUTF8;
  late final JSFunction TextCopy;
  late final JSFunction TextIsEqual;
  late final JSFunction TextLength;
  late final JSFunction TextFormat;
  late final JSFunction TextSubtext;
  late final JSFunction TextReplace;
  late final JSFunction TextInsert;
  late final JSFunction TextJoin;
  late final JSFunction TextSplit;
  late final JSFunction TextAppend;
  late final JSFunction TextFindIndex;
  late final JSFunction TextToUpper;
  late final JSFunction TextToLower;
  late final JSFunction TextToPascal;
  late final JSFunction TextToSnake;
  late final JSFunction TextToCamel;
  late final JSFunction TextToInteger;
  late final JSFunction TextToFloat;
  late final JSFunction DrawLine3D;
  late final JSFunction DrawPoint3D;
  late final JSFunction DrawCircle3D;
  late final JSFunction DrawTriangle3D;
  late final JSFunction DrawTriangleStrip3D;
  late final JSFunction DrawCube;
  late final JSFunction DrawCubeV;
  late final JSFunction DrawCubeWires;
  late final JSFunction DrawCubeWiresV;
  late final JSFunction DrawSphere;
  late final JSFunction DrawSphereEx;
  late final JSFunction DrawSphereWires;
  late final JSFunction DrawCylinder;
  late final JSFunction DrawCylinderEx;
  late final JSFunction DrawCylinderWires;
  late final JSFunction DrawCylinderWiresEx;
  late final JSFunction DrawCapsule;
  late final JSFunction DrawCapsuleWires;
  late final JSFunction DrawPlane;
  late final JSFunction DrawRay;
  late final JSFunction DrawGrid;
  late final JSFunction LoadModel;
  late final JSFunction LoadModelFromMesh;
  late final JSFunction IsModelValid;
  late final JSFunction UnloadModel;
  late final JSFunction GetModelBoundingBox;
  late final JSFunction DrawModel;
  late final JSFunction DrawModelEx;
  late final JSFunction DrawModelWires;
  late final JSFunction DrawModelWiresEx;
  late final JSFunction DrawModelPoints;
  late final JSFunction DrawModelPointsEx;
  late final JSFunction DrawBoundingBox;
  late final JSFunction DrawBillboard;
  late final JSFunction DrawBillboardRec;
  late final JSFunction DrawBillboardPro;
  late final JSFunction UploadMesh;
  late final JSFunction UpdateMeshBuffer;
  late final JSFunction UnloadMesh;
  late final JSFunction DrawMesh;
  late final JSFunction DrawMeshInstanced;
  late final JSFunction GetMeshBoundingBox;
  late final JSFunction GenMeshTangents;
  late final JSFunction ExportMesh;
  late final JSFunction ExportMeshAsCode;
  late final JSFunction GenMeshPoly;
  late final JSFunction GenMeshPlane;
  late final JSFunction GenMeshCube;
  late final JSFunction GenMeshSphere;
  late final JSFunction GenMeshHemiSphere;
  late final JSFunction GenMeshCylinder;
  late final JSFunction GenMeshCone;
  late final JSFunction GenMeshTorus;
  late final JSFunction GenMeshKnot;
  late final JSFunction GenMeshHeightmap;
  late final JSFunction GenMeshCubicmap;
  late final JSFunction LoadMaterials;
  late final JSFunction LoadMaterialDefault;
  late final JSFunction IsMaterialValid;
  late final JSFunction UnloadMaterial;
  late final JSFunction SetMaterialTexture;
  late final JSFunction SetModelMeshMaterial;
  late final JSFunction LoadModelAnimations;
  late final JSFunction UpdateModelAnimation;
  late final JSFunction UpdateModelAnimationBones;
  late final JSFunction UnloadModelAnimation;
  late final JSFunction UnloadModelAnimations;
  late final JSFunction IsModelAnimationValid;
  late final JSFunction CheckCollisionSpheres;
  late final JSFunction CheckCollisionBoxes;
  late final JSFunction CheckCollisionBoxSphere;
  late final JSFunction GetRayCollisionSphere;
  late final JSFunction GetRayCollisionBox;
  late final JSFunction GetRayCollisionMesh;
  late final JSFunction GetRayCollisionTriangle;
  late final JSFunction GetRayCollisionQuad;

  RaylibCore(super.rl) {
    InitWindow = _module.dwrap('InitWindow', [n, n, s]);
    CloseWindow = _module.dwrap('CloseWindow', []);
    /*UNUSED*/WindowShouldClose = _module.dwrap('WindowShouldClose', [], n);
    IsWindowReady = _module.dwrap('IsWindowReady', [], n);
    IsWindowFullscreen = _module.dwrap('IsWindowFullscreen', [], n);
    IsWindowHidden = _module.dwrap('IsWindowHidden', [], n);
    IsWindowMinimized = _module.dwrap('IsWindowMinimized', [], n);
    IsWindowMaximized = _module.dwrap('IsWindowMaximized', [], n);
    IsWindowFocused = _module.dwrap('IsWindowFocused', [], n);
    IsWindowResized = _module.dwrap('IsWindowResized', [], n);
    IsWindowState = _module.dwrap('IsWindowState', [n], n);
    SetWindowState = _module.dwrap('SetWindowState', [n]);
    ClearWindowState = _module.dwrap('ClearWindowState', [n]);
    ToggleFullscreen = _module.dwrap('ToggleFullscreen', []);
    ToggleBorderlessWindowed = _module.dwrap('ToggleBorderlessWindowed', []);
    MaximizeWindow = _module.dwrap('MaximizeWindow', []);
    MinimizeWindow = _module.dwrap('MinimizeWindow', []);
    RestoreWindow = _module.dwrap('RestoreWindow', []);
    SetWindowIcon = _module.dwrap('SetWindowIcon', [n]);
    SetWindowIcons = _module.dwrap('SetWindowIcons', [n, n]);
    SetWindowTitle = _module.dwrap('SetWindowTitle', [s]);
    SetWindowPosition = _module.dwrap('SetWindowPosition', [n, n]);
    SetWindowMonitor = _module.dwrap('SetWindowMonitor', [n]);
    SetWindowMinSize = _module.dwrap('SetWindowMinSize', [n, n]);
    SetWindowMaxSize = _module.dwrap('SetWindowMaxSize', [n, n]);
    SetWindowSize = _module.dwrap('SetWindowSize', [n, n]);
    SetWindowOpacity = _module.dwrap('SetWindowOpacity', [n]);
    SetWindowFocused = _module.dwrap('SetWindowFocused', []);
    GetWindowHandle = _module.dwrap('GetWindowHandle', [], n);
    GetScreenWidth = _module.dwrap('GetScreenWidth', [], n);
    GetScreenHeight = _module.dwrap('GetScreenHeight', [], n);
    GetRenderWidth = _module.dwrap('GetRenderWidth', [], n);
    GetRenderHeight = _module.dwrap('GetRenderHeight', [], n);
    GetMonitorCount = _module.dwrap('GetMonitorCount', [], n);
    GetCurrentMonitor = _module.dwrap('GetCurrentMonitor', [], n);
    GetMonitorPosition = _module.dwrap('GetMonitorPosition', [n, n]);
    GetMonitorWidth = _module.dwrap('GetMonitorWidth', [n], n);
    GetMonitorHeight = _module.dwrap('GetMonitorHeight', [n], n);
    GetMonitorPhysicalWidth = _module.dwrap('GetMonitorPhysicalWidth', [n], n);
    GetMonitorPhysicalHeight = _module.dwrap('GetMonitorPhysicalHeight', [n], n);
    GetMonitorRefreshRate = _module.dwrap('GetMonitorRefreshRate', [n], n);
    GetWindowPosition = _module.dwrap('GetWindowPosition', [n]);
    GetWindowScaleDPI = _module.dwrap('GetWindowScaleDPI', [n]);
    GetMonitorName = _module.dwrap('GetMonitorName', [n], n);
    SetClipboardText = _module.dwrap('SetClipboardText', [s]);
    GetClipboardText = _module.dwrap('GetClipboardText', [], n);
    GetClipboardImage = _module.dwrap('GetClipboardImage', [n]);
    EnableEventWaiting = _module.dwrap('EnableEventWaiting', []);
    DisableEventWaiting = _module.dwrap('DisableEventWaiting', []);
    ShowCursor = _module.dwrap('ShowCursor', []);
    HideCursor = _module.dwrap('HideCursor', []);
    IsCursorHidden = _module.dwrap('IsCursorHidden', [], n);
    EnableCursor = _module.dwrap('EnableCursor', []);
    DisableCursor = _module.dwrap('DisableCursor', []);
    IsCursorOnScreen = _module.dwrap('IsCursorOnScreen', [], n);
    ClearBackground = _module.dwrap('ClearBackground', [n]);
    BeginDrawing = _module.dwrap('BeginDrawing', []);
    EndDrawing = _module.dwrap('EndDrawing', []);
    BeginMode2D = _module.dwrap('BeginMode2D', [n]);
    EndMode2D = _module.dwrap('EndMode2D', []);
    BeginMode3D = _module.dwrap('BeginMode3D', [n]);
    EndMode3D = _module.dwrap('EndMode3D', []);
    BeginTextureMode = _module.dwrap('BeginTextureMode', [n]);
    EndTextureMode = _module.dwrap('EndTextureMode', []);
    BeginShaderMode = _module.dwrap('BeginShaderMode', [n]);
    EndShaderMode = _module.dwrap('EndShaderMode', []);
    BeginBlendMode = _module.dwrap('BeginBlendMode', [n]);
    EndBlendMode = _module.dwrap('EndBlendMode', []);
    BeginScissorMode = _module.dwrap('BeginScissorMode', [n, n, n, n]);
    EndScissorMode = _module.dwrap('EndScissorMode', []);
    BeginVrStereoMode = _module.dwrap('BeginVrStereoMode', [n]);
    EndVrStereoMode = _module.dwrap('EndVrStereoMode', []);
    LoadVrStereoConfig = _module.dwrap('LoadVrStereoConfig', [n, n]);
    UnloadVrStereoConfig = _module.dwrap('UnloadVrStereoConfig', [n]);
    LoadShader = _module.dwrap('LoadShader', [n, s, s]);
    LoadShaderFromMemory = _module.dwrap('LoadShaderFromMemory', [n, s, s]);
    IsShaderValid = _module.dwrap('IsShaderValid', [n], n);
    GetShaderLocation = _module.dwrap('GetShaderLocation', [n, s], n);
    GetShaderLocationAttrib = _module.dwrap('GetShaderLocationAttrib', [n, s], n);
    SetShaderValue = _module.dwrap('SetShaderValue', [n, n, n, n]);
    SetShaderValueV = _module.dwrap('SetShaderValueV', [n, n, n, n, n]);
    SetShaderValueMatrix = _module.dwrap('SetShaderValueMatrix', [n, n, n]);
    SetShaderValueTexture = _module.dwrap('SetShaderValueTexture', [n, n, n]);
    UnloadShader = _module.dwrap('UnloadShader', [n]);
    GetScreenToWorldRay = _module.dwrap('GetScreenToWorldRay', [n, n, n]);
    GetScreenToWorldRayEx = _module.dwrap('GetScreenToWorldRayEx', [n, n, n, n, n]);
    GetWorldToScreen = _module.dwrap('GetWorldToScreen', [n, n, n]);
    GetWorldToScreenEx = _module.dwrap('GetWorldToScreenEx', [n, n, n, n, n]);
    GetWorldToScreen2D = _module.dwrap('GetWorldToScreen2D', [n, n, n]);
    GetScreenToWorld2D = _module.dwrap('GetScreenToWorld2D', [n, n, n]);
    GetCameraMatrix = _module.dwrap('GetCameraMatrix', [n, n]);
    GetCameraMatrix2D = _module.dwrap('GetCameraMatrix2D', [n, n]);
    SetTargetFPS = _module.dwrap('SetTargetFPS', [n]);
    GetFrameTime = _module.dwrap('GetFrameTime', [], n);
    GetTime = _module.dwrap('GetTime', [], n);
    GetFPS = _module.dwrap('GetFPS', [], n);
    SwapScreenBuffer = _module.dwrap('SwapScreenBuffer', []);
    PollInputEvents = _module.dwrap('PollInputEvents', []);
    WaitTime = _module.dwrap('WaitTime', [n]);
    SetRandomSeed = _module.dwrap('SetRandomSeed', [n]);
    GetRandomValue = _module.dwrap('GetRandomValue', [n, n], n);
    /*UNUSED*/LoadRandomSequence = _module.dwrap('LoadRandomSequence', [n, n, n], n);
    /*UNUSED*/UnloadRandomSequence = _module.dwrap('UnloadRandomSequence', [n]);
    TakeScreenshot = _module.dwrap('TakeScreenshot', [s]);
    SetConfigFlags = _module.dwrap('SetConfigFlags', [n]);
    OpenURL = _module.dwrap('OpenURL', [s]);
    TraceLog = _module.dwrap('TraceLog', [n, s]);
    SetTraceLogLevel = _module.dwrap('SetTraceLogLevel', [n]);
    SetLoadFileDataCallback = _module.dwrap('SetLoadFileDataCallback', [n]);
    SetSaveFileDataCallback = _module.dwrap('SetSaveFileDataCallback', [n]);
    SetLoadFileTextCallback = _module.dwrap('SetLoadFileTextCallback', [n]);
    SetSaveFileTextCallback = _module.dwrap('SetSaveFileTextCallback', [n]);
    LoadFileData = _module.dwrap('LoadFileData', [s, n], n);
    UnloadFileData = _module.dwrap('UnloadFileData', [n]);
    SaveFileData = _module.dwrap('SaveFileData', [s, n, n], n);
    ExportDataAsCode = _module.dwrap('ExportDataAsCode', [n, n, s], n);
    LoadFileText = _module.dwrap('LoadFileText', [s], n);
    UnloadFileText = _module.dwrap('UnloadFileText', [n]);
    SaveFileText = _module.dwrap('SaveFileText', [s, s], n);
    FileExists = _module.dwrap('FileExists', [s], n);
    DirectoryExists = _module.dwrap('DirectoryExists', [s], n);
    IsFileExtension = _module.dwrap('IsFileExtension', [s, s]);
    GetFileLength = _module.dwrap('GetFileLength', [s], n);
    GetFileExtension = _module.dwrap('GetFileExtension', [s], n);
    GetFileName = _module.dwrap('GetFileName', [s], n);
    GetFileNameWithoutExt = _module.dwrap('GetFileNameWithoutExt', [s], n);
    GetDirectoryPath = _module.dwrap('GetDirectoryPath', [s], n);
    GetPrevDirectoryPath = _module.dwrap('GetPrevDirectoryPath', [s], n);
    GetWorkingDirectory = _module.dwrap('GetWorkingDirectory', [], n);
    GetApplicationDirectory = _module.dwrap('GetApplicationDirectory', [], n);
    MakeDirectory = _module.dwrap('MakeDirectory', [s], n);
    ChangeDirectory = _module.dwrap('ChangeDirectory', [s], n);
    IsPathFile = _module.dwrap('IsPathFile', [s], n);
    IsFileNameValid = _module.dwrap('IsFileNameValid', [s], n);
    LoadDirectoryFiles = _module.dwrap('LoadDirectoryFiles', [n, s]);
    LoadDirectoryFilesEx = _module.dwrap('LoadDirectoryFilesEx', [n, s, s, n]);
    UnloadDirectoryFiles = _module.dwrap('UnloadDirectoryFiles', [n]);
    IsFileDropped = _module.dwrap('IsFileDropped', [], n);
    LoadDroppedFiles = _module.dwrap('LoadDroppedFiles', [n]);
    UnloadDroppedFiles = _module.dwrap('UnloadDroppedFiles', [n]);
    GetFileModTime = _module.dwrap('GetFileModTime', [s]);
    CompressData = _module.dwrap('CompressData', [n, n, n], n);
    DecompressData = _module.dwrap('DecompressData', [n, n, n], n);
    EncodeDataBase64 = _module.dwrap('EncodeDataBase64', [n, n, n], n);
    DecodeDataBase64 = _module.dwrap('DecodeDataBase64', [n, n], n);
    ComputeCRC32 = _module.dwrap('ComputeCRC32', [n, n]);
    ComputeMD5 = _module.dwrap('ComputeMD5', [n, n]);
    ComputeSHA1 = _module.dwrap('ComputeSHA1', [n, n]);
    LoadAutomationEventList = _module.dwrap('LoadAutomationEventList', [n, s]);
    UnloadAutomationEventList = _module.dwrap('UnloadAutomationEventList', [n]);
    ExportAutomationEventList = _module.dwrap('ExportAutomationEventList', [n, s]);
    SetAutomationEventList = _module.dwrap('SetAutomationEventList', [n]);
    SetAutomationEventBaseFrame = _module.dwrap('SetAutomationEventBaseFrame', [n]);
    StartAutomationEventRecording = _module.dwrap('StartAutomationEventRecording', []);
    StopAutomationEventRecording = _module.dwrap('StopAutomationEventRecording', []);
    PlayAutomationEvent = _module.dwrap('PlayAutomationEvent', [n]);
    IsKeyPressed = _module.dwrap('IsKeyPressed', [n], n);
    IsKeyPressedRepeat = _module.dwrap('IsKeyPressedRepeat', [n], n);
    IsKeyDown = _module.dwrap('IsKeyDown', [n], n);
    IsKeyReleased = _module.dwrap('IsKeyReleased', [n], n);
    IsKeyUp = _module.dwrap('IsKeyUp', [n], n);
    GetKeyPressed = _module.dwrap('GetKeyPressed', [], n);
    GetCharPressed = _module.dwrap('GetCharPressed', [], n);
    SetExitKey = _module.dwrap('SetExitKey', [n]);
    IsGamepadAvailable = _module.dwrap('IsGamepadAvailable', [n], n);
    GetGamepadName = _module.dwrap('GetGamepadName', [n], n);
    IsGamepadButtonPressed = _module.dwrap('IsGamepadButtonPressed', [n, n], n);
    IsGamepadButtonDown = _module.dwrap('IsGamepadButtonDown', [n, n], n);
    IsGamepadButtonReleased = _module.dwrap('IsGamepadButtonReleased', [n, n], n);
    IsGamepadButtonUp = _module.dwrap('IsGamepadButtonUp', [n, n], n);
    GetGamepadButtonPressed = _module.dwrap('GetGamepadButtonPressed', [], n);
    GetGamepadAxisCount = _module.dwrap('GetGamepadAxisCount', [n], n);
    GetGamepadAxisMovement = _module.dwrap('GetGamepadAxisMovement', [n, n], n);
    SetGamepadMappings = _module.dwrap('SetGamepadMappings', [s], n);
    SetGamepadVibration = _module.dwrap('SetGamepadVibration', [n, n, n, n]);
    IsMouseButtonPressed = _module.dwrap('IsMouseButtonPressed', [n], n);
    IsMouseButtonDown = _module.dwrap('IsMouseButtonDown', [n], n);
    IsMouseButtonReleased = _module.dwrap('IsMouseButtonReleased', [n], n);
    IsMouseButtonUp = _module.dwrap('IsMouseButtonUp', [n], n);
    GetMouseX = _module.dwrap('GetMouseX', [], n);
    GetMouseY = _module.dwrap('GetMouseY', [], n);
    GetMousePosition = _module.dwrap('GetMousePosition', [n]);
    GetMouseDelta = _module.dwrap('GetMouseDelta', [n]);
    SetMousePosition = _module.dwrap('SetMousePosition', [n, n]);
    SetMouseOffset = _module.dwrap('SetMouseOffset', [n, n]);
    SetMouseScale = _module.dwrap('SetMouseScale', [n, n]);
    GetMouseWheelMove = _module.dwrap('GetMouseWheelMove', [], n);
    GetMouseWheelMoveV = _module.dwrap('GetMouseWheelMoveV', [n]);
    SetMouseCursor = _module.dwrap('SetMouseCursor', [n]);
    GetTouchX = _module.dwrap('GetTouchX', [], n);
    GetTouchY = _module.dwrap('GetTouchY', [], n);
    GetTouchPosition = _module.dwrap('GetTouchPosition', [n, n]);
    GetTouchPointId = _module.dwrap('GetTouchPointId', [n], n);
    GetTouchPointCount = _module.dwrap('GetTouchPointCount', [], n);
    SetGesturesEnabled = _module.dwrap('SetGesturesEnabled', [n]);
    IsGestureDetected = _module.dwrap('IsGestureDetected', [n], n);
    GetGestureDetected = _module.dwrap('GetGestureDetected', [], n);
    GetGestureHoldDuration = _module.dwrap('GetGestureHoldDuration', [], n);
    GetGestureDragVector = _module.dwrap('GetGestureDragVector', [n]);
    GetGestureDragAngle = _module.dwrap('GetGestureDragAngle', [], n);
    GetGesturePinchVector = _module.dwrap('GetGesturePinchVector', [n]);
    GetGesturePinchAngle = _module.dwrap('GetGesturePinchAngle', [], n);
    UpdateCamera = _module.dwrap('UpdateCamera', [n, n]);
    UpdateCameraPro = _module.dwrap('UpdateCameraPro', [n, n, n, n]);
    SetShapesTexture = _module.dwrap('SetShapesTexture', [n, n]);
    GetShapesTexture = _module.dwrap('GetShapesTexture', [n]);
    GetShapesTextureRectangle = _module.dwrap('GetShapesTextureRectangle', [n]);
    DrawPixel = _module.dwrap('DrawPixel', [n, n, n]);
    DrawPixelV = _module.dwrap('DrawPixelV', [n, n]);
    DrawLine = _module.dwrap('DrawLine', [n, n, n, n, n]);
    DrawLineV = _module.dwrap('DrawLineV', [n, n, n]);
    DrawLineEx = _module.dwrap('DrawLineEx', [n, n, n, n]);
    DrawLineStrip = _module.dwrap('DrawLineStrip', [n, n, n]);
    DrawLineBezier = _module.dwrap('DrawLineBezier', [n, n, n, n]);
    DrawCircle = _module.dwrap('DrawCircle', [n, n, n, n]);
    DrawCircleSector = _module.dwrap('DrawCircleSector', [n, n, n, n, n, n]);
    DrawCircleSectorLines = _module.dwrap('DrawCircleSectorLines', [n, n, n, n, n, n]);
    DrawCircleGradient = _module.dwrap('DrawCircleGradient', [n, n, n, n, n]);
    DrawCircleV = _module.dwrap('DrawCircleV', [n, n, n]);
    DrawCircleLines = _module.dwrap('DrawCircleLines', [n, n, n, n]);
    DrawCircleLinesV = _module.dwrap('DrawCircleLinesV', [n, n, n]);
    DrawEllipse = _module.dwrap('DrawEllipse', [n, n, n, n, n]);
    DrawEllipseLines = _module.dwrap('DrawEllipseLines', [n, n, n, n, n]);
    DrawRing = _module.dwrap('DrawRing', [n, n, n, n, n, n, n]);
    DrawRingLines = _module.dwrap('DrawRingLines', [n, n, n, n, n, n, n]);
    DrawRectangle = _module.dwrap('DrawRectangle', [n, n, n, n, n]);
    DrawRectangleV = _module.dwrap('DrawRectangleV', [n, n, n]);
    DrawRectangleRec = _module.dwrap('DrawRectangleRec', [n, n]);
    DrawRectanglePro = _module.dwrap('DrawRectanglePro', [n, n, n, n]);
    DrawRectangleGradientV = _module.dwrap('DrawRectangleGradientV', [n, n, n, n, n, n]);
    DrawRectangleGradientH = _module.dwrap('DrawRectangleGradientH', [n, n, n, n, n, n]);
    DrawRectangleGradientEx = _module.dwrap('DrawRectangleGradientEx', [n, n, n, n, n]);
    DrawRectangleLines = _module.dwrap('DrawRectangleLines', [n, n, n, n, n]);
    DrawRectangleLinesEx = _module.dwrap('DrawRectangleLinesEx', [n, n, n]);
    DrawRectangleRounded = _module.dwrap('DrawRectangleRounded', [n, n, n, n]);
    DrawRectangleRoundedLines = _module.dwrap('DrawRectangleRoundedLines', [n, n, n, n]);
    DrawRectangleRoundedLinesEx = _module.dwrap('DrawRectangleRoundedLinesEx', [n, n, n, n, n]);
    DrawTriangle = _module.dwrap('DrawTriangle', [n, n, n, n]);
    DrawTriangleLines = _module.dwrap('DrawTriangleLines', [n, n, n, n]);
    DrawTriangleFan = _module.dwrap('DrawTriangleFan', [n, n, n]);
    DrawTriangleStrip = _module.dwrap('DrawTriangleStrip', [n, n, n]);
    DrawPoly = _module.dwrap('DrawPoly', [n, n, n, n, n]);
    DrawPolyLines = _module.dwrap('DrawPolyLines', [n, n, n, n, n]);
    DrawPolyLinesEx = _module.dwrap('DrawPolyLinesEx', [n, n, n, n, n, n]);
    DrawSplineLinear = _module.dwrap('DrawSplineLinear', [n, n, n, n]);
    DrawSplineBasis = _module.dwrap('DrawSplineBasis', [n, n, n, n]);
    DrawSplineCatmullRom = _module.dwrap('DrawSplineCatmullRom', [n, n, n, n]);
    DrawSplineBezierQuadratic = _module.dwrap('DrawSplineBezierQuadratic', [n, n, n, n]);
    DrawSplineBezierCubic = _module.dwrap('DrawSplineBezierCubic', [n, n, n, n]);
    DrawSplineSegmentLinear = _module.dwrap('DrawSplineSegmentLinear', [n, n, n, n]);
    DrawSplineSegmentBasis = _module.dwrap('DrawSplineSegmentBasis', [n, n, n, n, n, n]);
    DrawSplineSegmentCatmullRom = _module.dwrap('DrawSplineSegmentCatmullRom', [n, n, n, n, n, n]);
    DrawSplineSegmentBezierQuadratic = _module.dwrap('DrawSplineSegmentBezierQuadratic', [n, n, n, n, n]);
    DrawSplineSegmentBezierCubic = _module.dwrap('DrawSplineSegmentBezierCubic', [n, n, n, n, n, n]);
    GetSplinePointLinear = _module.dwrap('GetSplinePointLinear', [n, n, n, n]);
    GetSplinePointBasis = _module.dwrap('GetSplinePointBasis', [n, n, n, n, n, n]);
    GetSplinePointCatmullRom = _module.dwrap('GetSplinePointCatmullRom', [n, n, n, n, n, n]);
    GetSplinePointBezierQuad = _module.dwrap('GetSplinePointBezierQuad', [n, n, n, n, n]);
    GetSplinePointBezierCubic = _module.dwrap('GetSplinePointBezierCubic', [n, n, n, n, n, n]);
    CheckCollisionRecs = _module.dwrap('CheckCollisionRecs', [n, n], n);
    CheckCollisionCircles = _module.dwrap('CheckCollisionCircles', [n, n, n, n], n);
    CheckCollisionCircleRec = _module.dwrap('CheckCollisionCircleRec', [n, n, n], n);
    CheckCollisionCircleLine = _module.dwrap('CheckCollisionCircleLine', [n, n, n, n], n);
    CheckCollisionPointRec = _module.dwrap('CheckCollisionPointRec', [n, n], n);
    CheckCollisionPointCircle = _module.dwrap('CheckCollisionPointCircle', [n, n, n], n);
    CheckCollisionPointTriangle = _module.dwrap('CheckCollisionPointTriangle', [n, n, n, n], n);
    CheckCollisionPointLine = _module.dwrap('CheckCollisionPointLine', [n, n, n, n], n);
    CheckCollisionPointPoly = _module.dwrap('CheckCollisionPointPoly', [n, n, n], n);
    CheckCollisionLines = _module.dwrap('CheckCollisionLines', [n, n, n, n, n], n);
    GetCollisionRec = _module.dwrap('GetCollisionRec', [n, n, n]);
    LoadImage = _module.dwrap('LoadImage', [n, s]);
    LoadImageRaw = _module.dwrap('LoadImageRaw', [n, s, n, n, n, n]);
    LoadImageAnim = _module.dwrap('LoadImageAnim', [n, s, n]);
    LoadImageAnimFromMemory = _module.dwrap('LoadImageAnimFromMemory', [n, s, n, n, n]);
    LoadImageFromMemory = _module.dwrap('LoadImageFromMemory', [n, s, n, n]);
    LoadImageFromTexture = _module.dwrap('LoadImageFromTexture', [n, n]);
    LoadImageFromScreen = _module.dwrap('LoadImageFromScreen', [n]);
    IsImageValid = _module.dwrap('IsImageValid', [n], n);
    UnloadImage = _module.dwrap('UnloadImage', [n]);
    ExportImage = _module.dwrap('ExportImage', [n, s], n);
    ExportImageToMemory = _module.dwrap('ExportImageToMemory', [n, s, n], n);
    ExportImageAsCode = _module.dwrap('ExportImageAsCode', [n, s], n);
    GenImageColor = _module.dwrap('GenImageColor', [n, n, n, n]);
    GenImageGradientLinear = _module.dwrap('GenImageGradientLinear', [n, n, n, n, n, n]);
    GenImageGradientRadial = _module.dwrap('GenImageGradientRadial', [n, n, n, n, n, n]);
    GenImageGradientSquare = _module.dwrap('GenImageGradientSquare', [n, n, n, n, n, n]);
    GenImageChecked = _module.dwrap('GenImageChecked', [n, n, n, n, n, n, n]);
    GenImageWhiteNoise = _module.dwrap('GenImageWhiteNoise', [n, n, n, n]);
    GenImagePerlinNoise = _module.dwrap('GenImagePerlinNoise', [n, n, n, n, n, n]);
    GenImageCellular = _module.dwrap('GenImageCellular', [n, n, n, n]);
    GenImageText = _module.dwrap('GenImageText', [n, n, n, s]);
    ImageCopy = _module.dwrap('ImageCopy', [n, n]);
    ImageFromImage = _module.dwrap('ImageFromImage', [n, n, n]);
    ImageFromChannel = _module.dwrap('ImageFromChannel', [n, n, n]);
    ImageText = _module.dwrap('ImageText', [n, s, n, n]);
    ImageTextEx = _module.dwrap('ImageTextEx', [n, n, s, n, n, n]);
    ImageFormat = _module.dwrap('ImageFormat', [n, n]);
    ImageToPOT = _module.dwrap('ImageToPOT', [n, n]);
    ImageCrop = _module.dwrap('ImageCrop', [n, n]);
    ImageAlphaCrop = _module.dwrap('ImageAlphaCrop', [n, n]);
    ImageAlphaClear = _module.dwrap('ImageAlphaClear', [n, n, n]);
    ImageAlphaMask = _module.dwrap('ImageAlphaMask', [n, n]);
    ImageAlphaPremultiply = _module.dwrap('ImageAlphaPremultiply', [n]);
    ImageBlurGaussian = _module.dwrap('ImageBlurGaussian', [n, n]);
    ImageKernelConvolution = _module.dwrap('ImageKernelConvolution', [n, n, n]);
    ImageResize = _module.dwrap('ImageResize', [n, n, n]);
    ImageResizeNN = _module.dwrap('ImageResizeNN', [n, n, n]);
    ImageResizeCanvas = _module.dwrap('ImageResizeCanvas', [n, n, n, n, n, n]);
    ImageMipmaps = _module.dwrap('ImageMipmaps', [n]);
    ImageDither = _module.dwrap('ImageDither', [n, n, n, n, n]);
    ImageFlipVertical = _module.dwrap('ImageFlipVertical', [n]);
    ImageFlipHorizontal = _module.dwrap('ImageFlipHorizontal', [n]);
    ImageRotate = _module.dwrap('ImageRotate', [n, n]);
    ImageRotateCW = _module.dwrap('ImageRotateCW', [n]);
    ImageRotateCCW = _module.dwrap('ImageRotateCCW', [n]);
    ImageColorTint = _module.dwrap('ImageColorTint', [n, n]);
    ImageColorInvert = _module.dwrap('ImageColorInvert', [n]);
    ImageColorGrayscale = _module.dwrap('ImageColorGrayscale', [n]);
    ImageColorContrast = _module.dwrap('ImageColorContrast', [n, n]);
    ImageColorBrightness = _module.dwrap('ImageColorBrightness', [n, n]);
    ImageColorReplace = _module.dwrap('ImageColorReplace', [n, n, n]);
    LoadImageColors = _module.dwrap('LoadImageColors', [n], n);
    LoadImagePalette = _module.dwrap('LoadImagePalette', [n, n, n], n);
    UnloadImageColors = _module.dwrap('UnloadImageColors', [n]);
    UnloadImagePalette = _module.dwrap('UnloadImagePalette', [n]);
    GetImageAlphaBorder = _module.dwrap('GetImageAlphaBorder', [n, n, n]);
    GetImageColor = _module.dwrap('GetImageColor', [n, n, n, n]);
    ImageClearBackground = _module.dwrap('ImageClearBackground', [n, n]);
    ImageDrawPixel = _module.dwrap('ImageDrawPixel', [n, n, n, n]);
    ImageDrawPixelV = _module.dwrap('ImageDrawPixelV', [n, n, n]);
    ImageDrawLine = _module.dwrap('ImageDrawLine', [n, n, n, n, n, n]);
    ImageDrawLineV = _module.dwrap('ImageDrawLineV', [n, n, n, n]);
    ImageDrawLineEx = _module.dwrap('ImageDrawLineEx', [n, n, n, n, n]);
    ImageDrawCircle = _module.dwrap('ImageDrawCircle', [n, n, n, n, n]);
    ImageDrawCircleV = _module.dwrap('ImageDrawCircleV', [n, n, n, n]);
    ImageDrawCircleLines = _module.dwrap('ImageDrawCircleLines', [n, n, n, n, n]);
    ImageDrawCircleLinesV = _module.dwrap('ImageDrawCircleLinesV', [n, n, n, n]);
    ImageDrawRectangle = _module.dwrap('ImageDrawRectangle', [n, n, n, n, n, n]);
    ImageDrawRectangleV = _module.dwrap('ImageDrawRectangleV', [n, n, n, n]);
    ImageDrawRectangleRec = _module.dwrap('ImageDrawRectangleRec', [n, n, n]);
    ImageDrawRectangleLines = _module.dwrap('ImageDrawRectangleLines', [n, n, n, n]);
    ImageDrawTriangle = _module.dwrap('ImageDrawTriangle', [n, n, n, n, n]);
    ImageDrawTriangleEx = _module.dwrap('ImageDrawTriangleEx', [n, n, n, n, n, n, n]);
    ImageDrawTriangleLines = _module.dwrap('ImageDrawTriangleLines', [n, n, n, n, n]);
    ImageDrawTriangleFan = _module.dwrap('ImageDrawTriangleFan', [n, n, n, n]);
    ImageDrawTriangleStrip = _module.dwrap('ImageDrawTriangleStrip', [n, n, n, n]);
    ImageDraw = _module.dwrap('ImageDraw', [n, n, n, n, n]);
    ImageDrawText = _module.dwrap('ImageDrawText', [n, s, n, n, n, n]);
    ImageDrawTextEx = _module.dwrap('ImageDrawTextEx', [n, n, s, n, n, n, n]);
    LoadTexture = _module.dwrap('LoadTexture', [n, s]);
    LoadTextureFromImage = _module.dwrap('LoadTextureFromImage', [n, n]);
    LoadTextureCubemap = _module.dwrap('LoadTextureCubemap', [n, n, n]);
    LoadRenderTexture = _module.dwrap('LoadRenderTexture', [n, n, n]);
    IsTextureValid = _module.dwrap('IsTextureValid', [n], n);
    UnloadTexture = _module.dwrap('UnloadTexture', [n]);
    IsRenderTextureValid = _module.dwrap('IsRenderTextureValid', [n], n);
    UnloadRenderTexture = _module.dwrap('UnloadRenderTexture', [n]);
    UpdateTexture = _module.dwrap('UpdateTexture', [n, n]);
    UpdateTextureRec = _module.dwrap('UpdateTextureRec', [n, n, n]);
    GenTextureMipmaps = _module.dwrap('GenTextureMipmaps', [n]);
    SetTextureFilter = _module.dwrap('SetTextureFilter', [n, n]);
    SetTextureWrap = _module.dwrap('SetTextureWrap', [n, n]);
    DrawTexture = _module.dwrap('DrawTexture', [n, n, n, n]);
    DrawTextureV = _module.dwrap('DrawTextureV', [n, n, n]);
    DrawTextureEx = _module.dwrap('DrawTextureEx', [n, n, n, n, n]);
    DrawTextureRec = _module.dwrap('DrawTextureRec', [n, n, n, n]);
    DrawTexturePro = _module.dwrap('DrawTexturePro', [n, n, n, n, n, n]);
    DrawTextureNPatch = _module.dwrap('DrawTextureNPatch', [n, n, n, n, n, n]);
    ColorIsEqual = _module.dwrap('ColorIsEqual', [n, n], n);
    Fade = _module.dwrap('Fade', [n, n, n]);
    ColorToInt = _module.dwrap('ColorToInt', [n], n);
    ColorNormalize = _module.dwrap('ColorNormalize', [n, n]);
    ColorFromNormalized = _module.dwrap('ColorFromNormalized', [n, n]);
    ColorToHSV = _module.dwrap('ColorToHSV', [n, n]);
    ColorFromHSV = _module.dwrap('ColorFromHSV', [n, n, n, n]);
    ColorTint = _module.dwrap('ColorTint', [n, n, n]);
    ColorBrightness = _module.dwrap('ColorBrightness', [n, n, n]);
    ColorContrast = _module.dwrap('ColorContrast', [n, n, n]);
    ColorAlpha = _module.dwrap('ColorAlpha', [n, n, n]);
    ColorAlphaBlend = _module.dwrap('ColorAlphaBlend', [n, n, n, n]);
    ColorLerp = _module.dwrap('ColorLerp', [n, n, n, n]);
    GetColor = _module.dwrap('GetColor', [n, n]);
    /*UNUSED*/GetPixelColor = _module.dwrap('GetPixelColor', [n, n, n]);
    /*UNUSED*/SetPixelColor = _module.dwrap('SetPixelColor', [n, n, n]);
    GetPixelDataSize = _module.dwrap('GetPixelDataSize', [n, n, n], n);
    GetFontDefault = _module.dwrap('GetFontDefault', [n]);
    LoadFont = _module.dwrap('LoadFont', [n, s]);
    LoadFontEx = _module.dwrap('LoadFontEx', [n, s, n, n, n]);
    LoadFontFromImage = _module.dwrap('LoadFontFromImage', [n, n, n, n]);
    LoadFontFromMemory = _module.dwrap('LoadFontFromMemory', [n, s, n, n, n, n, n]);
    IsFontValid = _module.dwrap('IsFontValid', [n], n);
    LoadFontData = _module.dwrap('LoadFontData', [n, n, n, n, n, n], n);
    GenImageFontAtlas = _module.dwrap('GenImageFontAtlas', [n, n, n, n, n, n, n]);
    UnloadFontData = _module.dwrap('UnloadFontData', [n, n]);
    UnloadFont = _module.dwrap('UnloadFont', [n]);
    ExportFontAsCode = _module.dwrap('ExportFontAsCode', [n, s], n);
    DrawFPS = _module.dwrap('DrawFPS', [n, n]);
    DrawText = _module.dwrap('DrawText', [s, n, n, n, n]);
    DrawTextEx = _module.dwrap('DrawTextEx', [n, s, n, n, n, n]);
    DrawTextPro = _module.dwrap('DrawTextPro', [n, s, n, n, n, n, n, n]);
    DrawTextCodepoint = _module.dwrap('DrawTextCodepoint', [n, n, n, n, n]);
    DrawTextCodepoints = _module.dwrap('DrawTextCodepoints', [n, n, n, n, n, n, n]);
    SetTextLineSpacing = _module.dwrap('SetTextLineSpacing', [n]);
    MeasureText = _module.dwrap('MeasureText', [s, n], n);
    MeasureTextEx = _module.dwrap('MeasureTextEx', [n, n, s, n, n]);
    GetGlyphIndex = _module.dwrap('GetGlyphIndex', [n, n], n);
    GetGlyphInfo = _module.dwrap('GetGlyphInfo', [n, n, n]);
    GetGlyphAtlasRec = _module.dwrap('GetGlyphAtlasRec', [n, n, n]);
    LoadUTF8 = _module.dwrap('LoadUTF8', [n, n], n);
    UnloadUTF8 = _module.dwrap('UnloadUTF8', [n]);
    LoadCodepoints = _module.dwrap('LoadCodepoints', [s, n], n);
    UnloadCodepoints = _module.dwrap('UnloadCodepoints', [n]);
    GetCodepointCount = _module.dwrap('GetCodepointCount', [s], n);
    GetCodepoint = _module.dwrap('GetCodepoint', [s, n], n);
    GetCodepointNext = _module.dwrap('GetCodepointNext', [s, n], n);
    GetCodepointPrevious = _module.dwrap('GetCodepointPrevious', [s, n], n);
    CodepointToUTF8 = _module.dwrap('CodepointToUTF8', [n, n]);
    /*UNUSED*/TextCopy = _module.dwrap('TextCopy', [n, n], n);
    /*UNUSED*/TextIsEqual = _module.dwrap('TextIsEqual', [s, s], n);
    /*UNUSED*/TextLength = _module.dwrap('TextLength', [s], n);
    /*UNUSED*/TextFormat = _module.dwrap('TextFormat', [s], n);
    /*UNUSED*/TextSubtext = _module.dwrap('TextSubtext', [s, n, n], n);
    /*UNUSED*/TextReplace = _module.dwrap('TextReplace', [s, s, s], n);
    /*UNUSED*/TextInsert = _module.dwrap('TextInsert', [s, s, n], n);
    /*UNUSED*/TextJoin = _module.dwrap('TextJoin', [n, n, s], n);
    /*UNUSED*/TextSplit = _module.dwrap('TextSplit', [s, n, n], n);
    /*UNUSED*/TextAppend = _module.dwrap('TextAppend', [n, s, n]);
    /*UNUSED*/TextFindIndex = _module.dwrap('TextFindIndex', [s, s], n);
    /*UNUSED*/TextToUpper = _module.dwrap('TextToUpper', [s], n);
    /*UNUSED*/TextToLower = _module.dwrap('TextToLower', [s], n);
    /*UNUSED*/TextToPascal = _module.dwrap('TextToPascal', [s], n);
    /*UNUSED*/TextToSnake = _module.dwrap('TextToSnake', [s], n);
    /*UNUSED*/TextToCamel = _module.dwrap('TextToCamel', [s], n);
    /*UNUSED*/TextToInteger = _module.dwrap('TextToInteger', [s], n);
    /*UNUSED*/TextToFloat = _module.dwrap('TextToFloat', [s], n);
    DrawLine3D = _module.dwrap('DrawLine3D', [n, n, n]);
    DrawPoint3D = _module.dwrap('DrawPoint3D', [n, n]);
    DrawCircle3D = _module.dwrap('DrawCircle3D', [n, n, n, n, n]);
    DrawTriangle3D = _module.dwrap('DrawTriangle3D', [n, n, n, n]);
    DrawTriangleStrip3D = _module.dwrap('DrawTriangleStrip3D', [n, n, n]);
    DrawCube = _module.dwrap('DrawCube', [n, n, n, n, n]);
    DrawCubeV = _module.dwrap('DrawCubeV', [n, n, n]);
    DrawCubeWires = _module.dwrap('DrawCubeWires', [n, n, n, n, n]);
    DrawCubeWiresV = _module.dwrap('DrawCubeWiresV', [n, n, n]);
    DrawSphere = _module.dwrap('DrawSphere', [n, n, n]);
    DrawSphereEx = _module.dwrap('DrawSphereEx', [n, n, n, n, n]);
    DrawSphereWires = _module.dwrap('DrawSphereWires', [n, n, n, n, n]);
    DrawCylinder = _module.dwrap('DrawCylinder', [n, n, n, n, n, n]);
    DrawCylinderEx = _module.dwrap('DrawCylinderEx', [n, n, n, n, n, n]);
    DrawCylinderWires = _module.dwrap('DrawCylinderWires', [n, n, n, n, n, n]);
    DrawCylinderWiresEx = _module.dwrap('DrawCylinderWiresEx', [n, n, n, n, n, n]);
    DrawCapsule = _module.dwrap('DrawCapsule', [n, n, n, n, n, n]);
    DrawCapsuleWires = _module.dwrap('DrawCapsuleWires', [n, n, n, n, n, n]);
    DrawPlane = _module.dwrap('DrawPlane', [n, n, n]);
    DrawRay = _module.dwrap('DrawRay', [n, n]);
    DrawGrid = _module.dwrap('DrawGrid', [n, n]);
    LoadModel = _module.dwrap('LoadModel', [n, s]);
    LoadModelFromMesh = _module.dwrap('LoadModelFromMesh', [n, n]);
    IsModelValid = _module.dwrap('IsModelValid', [n], n);
    UnloadModel = _module.dwrap('UnloadModel', [n]);
    GetModelBoundingBox = _module.dwrap('GetModelBoundingBox', [n, n]);
    DrawModel = _module.dwrap('DrawModel', [n, n, n, n]);
    DrawModelEx = _module.dwrap('DrawModelEx', [n, n, n, n, n, n]);
    DrawModelWires = _module.dwrap('DrawModelWires', [n, n, n, n]);
    DrawModelWiresEx = _module.dwrap('DrawModelWiresEx', [n, n, n, n, n, n]);
    DrawModelPoints = _module.dwrap('DrawModelPoints', [n, n, n, n]);
    DrawModelPointsEx = _module.dwrap('DrawModelPointsEx', [n, n, n, n, n, n]);
    DrawBoundingBox = _module.dwrap('DrawBoundingBox', [n, n]);
    DrawBillboard = _module.dwrap('DrawBillboard', [n, n, n, n, n]);
    DrawBillboardRec = _module.dwrap('DrawBillboardRec', [n, n, n, n, n, n]);
    DrawBillboardPro = _module.dwrap('DrawBillboardPro', [n, n, n, n, n, n, n, n, n]);
    UploadMesh = _module.dwrap('UploadMesh', [n, n]);
    UpdateMeshBuffer = _module.dwrap('UpdateMeshBuffer', [n, n, n, n, n]);
    UnloadMesh = _module.dwrap('UnloadMesh', [n]);
    DrawMesh = _module.dwrap('DrawMesh', [n, n, n]);
    DrawMeshInstanced = _module.dwrap('DrawMeshInstanced', [n, n, n, n]);
    GetMeshBoundingBox = _module.dwrap('GetMeshBoundingBox', [n, n]);
    GenMeshTangents = _module.dwrap('GenMeshTangents', [n]);
    ExportMesh = _module.dwrap('ExportMesh', [n, s], n);
    ExportMeshAsCode = _module.dwrap('ExportMeshAsCode', [n, s], n);
    GenMeshPoly = _module.dwrap('GenMeshPoly', [n, n, n]);
    GenMeshPlane = _module.dwrap('GenMeshPlane', [n, n, n, n, n]);
    GenMeshCube = _module.dwrap('GenMeshCube', [n, n, n, n]);
    GenMeshSphere = _module.dwrap('GenMeshSphere', [n, n, n, n]);
    GenMeshHemiSphere = _module.dwrap('GenMeshHemiSphere', [n, n, n, n]);
    GenMeshCylinder = _module.dwrap('GenMeshCylinder', [n, n, n, n]);
    GenMeshCone = _module.dwrap('GenMeshCone', [n, n, n, n]);
    GenMeshTorus = _module.dwrap('GenMeshTorus', [n, n, n, n, n]);
    GenMeshKnot = _module.dwrap('GenMeshKnot', [n, n, n, n, n]);
    GenMeshHeightmap = _module.dwrap('GenMeshHeightmap', [n, n, n]);
    GenMeshCubicmap = _module.dwrap('GenMeshCubicmap', [n, n, n]);
    LoadMaterials = _module.dwrap('LoadMaterials', [s, n], n);
    LoadMaterialDefault = _module.dwrap('LoadMaterialDefault', [n]);
    IsMaterialValid = _module.dwrap('IsMaterialValid', [n], n);
    UnloadMaterial = _module.dwrap('UnloadMaterial', [n]);
    SetMaterialTexture = _module.dwrap('SetMaterialTexture', [n, n, n]);
    SetModelMeshMaterial = _module.dwrap('SetModelMeshMaterial', [n, n, n]);
    LoadModelAnimations = _module.dwrap('LoadModelAnimations', [s, n], n);
    UpdateModelAnimation = _module.dwrap('UpdateModelAnimation', [n, n, n]);
    UpdateModelAnimationBones = _module.dwrap('UpdateModelAnimationBones', [n, n, n]);
    UnloadModelAnimation = _module.dwrap('UnloadModelAnimation', [n]);
    /*UNUSED*/UnloadModelAnimations = _module.dwrap('UnloadModelAnimations', [n, n]);
    IsModelAnimationValid = _module.dwrap('IsModelAnimationValid', [n, n], n);
    CheckCollisionSpheres = _module.dwrap('CheckCollisionSpheres', [n, n, n, n], n);
    CheckCollisionBoxes = _module.dwrap('CheckCollisionBoxes', [n, n], n);
    CheckCollisionBoxSphere = _module.dwrap('CheckCollisionBoxSphere', [n, n, n], n);
    GetRayCollisionSphere = _module.dwrap('GetRayCollisionSphere', [n, n, n, n]);
    GetRayCollisionBox = _module.dwrap('GetRayCollisionBox', [n, n, n]);
    GetRayCollisionMesh = _module.dwrap('GetRayCollisionMesh', [n, n, n, n]);
    GetRayCollisionTriangle = _module.dwrap('GetRayCollisionTriangle', [n, n, n, n, n]);
    GetRayCollisionQuad = _module.dwrap('GetRayCollisionQuad', [n, n, n, n, n, n]);
  }
}