part of '../../raylib_dartified_web.dart';

class RaylibRlgl extends RaylibModuleWasm with RaylibRlglModuleExtras<Raylib> {
  late final JSFunction rlMatrixMode;
  late final JSFunction rlPushMatrix;
  late final JSFunction rlPopMatrix;
  late final JSFunction rlLoadIdentity;
  late final JSFunction rlTranslatef;
  late final JSFunction rlRotatef;
  late final JSFunction rlScalef;
  late final JSFunction rlMultMatrixf;
  late final JSFunction rlFrustum;
  late final JSFunction rlOrtho;
  late final JSFunction rlViewport;
  late final JSFunction rlSetClipPlanes;
  late final JSFunction rlGetCullDistanceNear;
  late final JSFunction rlGetCullDistanceFar;
  late final JSFunction rlBegin;
  late final JSFunction rlEnd;
  late final JSFunction rlVertex2i;
  late final JSFunction rlVertex2f;
  late final JSFunction rlVertex3f;
  late final JSFunction rlTexCoord2f;
  late final JSFunction rlNormal3f;
  late final JSFunction rlColor4ub;
  late final JSFunction rlColor3f;
  late final JSFunction rlColor4f;
  late final JSFunction rlEnableVertexArray;
  late final JSFunction rlDisableVertexArray;
  late final JSFunction rlEnableVertexBuffer;
  late final JSFunction rlDisableVertexBuffer;
  late final JSFunction rlEnableVertexBufferElement;
  late final JSFunction rlDisableVertexBufferElement;
  late final JSFunction rlEnableVertexAttribute;
  late final JSFunction rlDisableVertexAttribute;
  late final JSFunction rlActiveTextureSlot;
  late final JSFunction rlEnableTexture;
  late final JSFunction rlDisableTexture;
  late final JSFunction rlEnableTextureCubemap;
  late final JSFunction rlDisableTextureCubemap;
  late final JSFunction rlTextureParameters;
  late final JSFunction rlCubemapParameters;
  late final JSFunction rlEnableShader;
  late final JSFunction rlDisableShader;
  late final JSFunction rlEnableFramebuffer;
  late final JSFunction rlDisableFramebuffer;
  late final JSFunction rlGetActiveFramebuffer;
  late final JSFunction rlActiveDrawBuffers;
  late final JSFunction rlBlitFramebuffer;
  late final JSFunction rlBindFramebuffer;
  late final JSFunction rlEnableColorBlend;
  late final JSFunction rlDisableColorBlend;
  late final JSFunction rlEnableDepthTest;
  late final JSFunction rlDisableDepthTest;
  late final JSFunction rlEnableDepthMask;
  late final JSFunction rlDisableDepthMask;
  late final JSFunction rlEnableBackfaceCulling;
  late final JSFunction rlDisableBackfaceCulling;
  late final JSFunction rlColorMask;
  late final JSFunction rlSetCullFace;
  late final JSFunction rlEnableScissorTest;
  late final JSFunction rlDisableScissorTest;
  late final JSFunction rlScissor;
  late final JSFunction rlEnableWireMode;
  late final JSFunction rlEnablePointMode;
  late final JSFunction rlDisableWireMode;
  late final JSFunction rlSetLineWidth;
  late final JSFunction rlGetLineWidth;
  late final JSFunction rlEnableSmoothLines;
  late final JSFunction rlDisableSmoothLines;
  late final JSFunction rlEnableStereoRender;
  late final JSFunction rlDisableStereoRender;
  late final JSFunction rlIsStereoRenderEnabled;
  late final JSFunction rlClearColor;
  late final JSFunction rlClearScreenBuffers;
  late final JSFunction rlCheckErrors;
  late final JSFunction rlSetBlendMode;
  late final JSFunction rlSetBlendFactors;
  late final JSFunction rlSetBlendFactorsSeparate;
  late final JSFunction rlglInit;
  late final JSFunction rlglClose;
  late final JSFunction rlLoadExtensions;
  late final JSFunction rlGetVersion;
  late final JSFunction rlSetFramebufferWidth;
  late final JSFunction rlGetFramebufferWidth;
  late final JSFunction rlSetFramebufferHeight;
  late final JSFunction rlGetFramebufferHeight;
  late final JSFunction rlGetTextureIdDefault;
  late final JSFunction rlGetShaderIdDefault;
  late final JSFunction rlGetShaderLocsDefault;
  late final JSFunction rlLoadRenderBatch;
  late final JSFunction rlUnloadRenderBatch;
  late final JSFunction rlDrawRenderBatch;
  late final JSFunction rlSetRenderBatchActive;
  late final JSFunction rlDrawRenderBatchActive;
  late final JSFunction rlCheckRenderBatchLimit;
  late final JSFunction rlSetTexture;
  late final JSFunction rlLoadVertexArray;
  late final JSFunction rlLoadVertexBuffer;
  late final JSFunction rlLoadVertexBufferElement;
  late final JSFunction rlUpdateVertexBuffer;
  late final JSFunction rlUpdateVertexBufferElements;
  late final JSFunction rlUnloadVertexArray;
  late final JSFunction rlUnloadVertexBuffer;
  late final JSFunction rlSetVertexAttribute;
  late final JSFunction rlSetVertexAttributeDivisor;
  late final JSFunction rlSetVertexAttributeDefault;
  late final JSFunction rlDrawVertexArray;
  late final JSFunction rlDrawVertexArrayElements;
  late final JSFunction rlDrawVertexArrayInstanced;
  late final JSFunction rlDrawVertexArrayElementsInstanced;
  late final JSFunction rlLoadTexture;
  late final JSFunction rlLoadTextureDepth;
  late final JSFunction rlLoadTextureCubemap;
  late final JSFunction rlUpdateTexture;
  late final JSFunction rlGetGlTextureFormats;
  late final JSFunction rlGetPixelFormatName;
  late final JSFunction rlUnloadTexture;
  late final JSFunction rlGenTextureMipmaps;
  late final JSFunction rlReadTexturePixels;
  late final JSFunction rlReadScreenPixels;
  late final JSFunction rlLoadFramebuffer;
  late final JSFunction rlFramebufferAttach;
  late final JSFunction rlFramebufferComplete;
  late final JSFunction rlUnloadFramebuffer;
  late final JSFunction rlLoadShaderCode;
  late final JSFunction rlCompileShader;
  late final JSFunction rlLoadShaderProgram;
  late final JSFunction rlUnloadShaderProgram;
  late final JSFunction rlGetLocationUniform;
  late final JSFunction rlGetLocationAttrib;
  late final JSFunction rlSetUniform;
  late final JSFunction rlSetUniformMatrix;
  late final JSFunction rlSetUniformMatrices;
  late final JSFunction rlSetUniformSampler;
  late final JSFunction rlSetShader;
  late final JSFunction rlLoadComputeShaderProgram;
  late final JSFunction rlComputeShaderDispatch;
  late final JSFunction rlLoadShaderBuffer;
  late final JSFunction rlUnloadShaderBuffer;
  late final JSFunction rlUpdateShaderBuffer;
  late final JSFunction rlBindShaderBuffer;
  late final JSFunction rlReadShaderBuffer;
  late final JSFunction rlCopyShaderBuffer;
  late final JSFunction rlGetShaderBufferSize;
  late final JSFunction rlBindImageTexture;
  late final JSFunction rlGetMatrixModelview;
  late final JSFunction rlGetMatrixProjection;
  late final JSFunction rlGetMatrixTransform;
  late final JSFunction rlGetMatrixProjectionStereo;
  late final JSFunction rlGetMatrixViewOffsetStereo;
  late final JSFunction rlSetMatrixProjection;
  late final JSFunction rlSetMatrixModelview;
  late final JSFunction rlSetMatrixProjectionStereo;
  late final JSFunction rlSetMatrixViewOffsetStereo;
  late final JSFunction rlLoadDrawCube;
  late final JSFunction rlLoadDrawQuad;

  RaylibRlgl(super.rl) {
    rlMatrixMode = _module.dwrap('rlMatrixMode', [n]);
    rlPushMatrix = _module.dwrap('rlPushMatrix', []);
    rlPopMatrix = _module.dwrap('rlPopMatrix', []);
    rlLoadIdentity = _module.dwrap('rlLoadIdentity', []);
    rlTranslatef = _module.dwrap('rlTranslatef', [n, n, n]);
    rlRotatef = _module.dwrap('rlRotatef', [n, n, n, n]);
    rlScalef = _module.dwrap('rlScalef', [n, n, n]);
    rlMultMatrixf = _module.dwrap('rlMultMatrixf', [n]);
    rlFrustum = _module.dwrap('rlFrustum', [n, n, n, n, n, n]);
    rlOrtho = _module.dwrap('rlOrtho', [n, n, n, n, n, n]);
    rlViewport = _module.dwrap('rlViewport', [n, n, n, n]);
    rlSetClipPlanes = _module.dwrap('rlSetClipPlanes', [n, n]);
    rlGetCullDistanceNear = _module.dwrap('rlGetCullDistanceNear', [], n);
    rlGetCullDistanceFar = _module.dwrap('rlGetCullDistanceFar', [], n);
    rlBegin = _module.dwrap('rlBegin', [n]);
    rlEnd = _module.dwrap('rlEnd', []);
    rlVertex2i = _module.dwrap('rlVertex2i', [n, n]);
    rlVertex2f = _module.dwrap('rlVertex2f', [n, n]);
    rlVertex3f = _module.dwrap('rlVertex3f', [n, n, n]);
    rlTexCoord2f = _module.dwrap('rlTexCoord2f', [n, n]);
    rlNormal3f = _module.dwrap('rlNormal3f', [n, n, n]);
    rlColor4ub = _module.dwrap('rlColor4ub', [n, n, n, n]);
    rlColor3f = _module.dwrap('rlColor3f', [n, n, n]);
    rlColor4f = _module.dwrap('rlColor4f', [n, n, n, n]);
    rlEnableVertexArray = _module.dwrap('rlEnableVertexArray', [n], n);
    rlDisableVertexArray = _module.dwrap('rlDisableVertexArray', []);
    rlEnableVertexBuffer = _module.dwrap('rlEnableVertexBuffer', [n]);
    rlDisableVertexBuffer = _module.dwrap('rlDisableVertexBuffer', []);
    rlEnableVertexBufferElement = _module.dwrap('rlEnableVertexBufferElement', [n]);
    rlDisableVertexBufferElement = _module.dwrap('rlDisableVertexBufferElement', []);
    rlEnableVertexAttribute = _module.dwrap('rlEnableVertexAttribute', [n]);
    rlDisableVertexAttribute = _module.dwrap('rlDisableVertexAttribute', [n]);
    rlActiveTextureSlot = _module.dwrap('rlActiveTextureSlot', [n]);
    rlEnableTexture = _module.dwrap('rlEnableTexture', [n]);
    rlDisableTexture = _module.dwrap('rlDisableTexture', []);
    rlEnableTextureCubemap = _module.dwrap('rlEnableTextureCubemap', [n]);
    rlDisableTextureCubemap = _module.dwrap('rlDisableTextureCubemap', []);
    rlTextureParameters = _module.dwrap('rlTextureParameters', [n, n, n]);
    rlCubemapParameters = _module.dwrap('rlCubemapParameters', [n, n, n]);
    rlEnableShader = _module.dwrap('rlEnableShader', [n]);
    rlDisableShader = _module.dwrap('rlDisableShader', []);
    rlEnableFramebuffer = _module.dwrap('rlEnableFramebuffer', [n]);
    rlDisableFramebuffer = _module.dwrap('rlDisableFramebuffer', []);
    rlGetActiveFramebuffer = _module.dwrap('rlGetActiveFramebuffer', [], n);
    rlActiveDrawBuffers = _module.dwrap('rlActiveDrawBuffers', [n]);
    rlBlitFramebuffer = _module.dwrap('rlBlitFramebuffer', [n, n, n, n, n, n, n, n, n]);
    rlBindFramebuffer = _module.dwrap('rlBindFramebuffer', [n, n]);
    rlEnableColorBlend = _module.dwrap('rlEnableColorBlend', []);
    rlDisableColorBlend = _module.dwrap('rlDisableColorBlend', []);
    rlEnableDepthTest = _module.dwrap('rlEnableDepthTest', []);
    rlDisableDepthTest = _module.dwrap('rlDisableDepthTest', []);
    rlEnableDepthMask = _module.dwrap('rlEnableDepthMask', []);
    rlDisableDepthMask = _module.dwrap('rlDisableDepthMask', []);
    rlEnableBackfaceCulling = _module.dwrap('rlEnableBackfaceCulling', []);
    rlDisableBackfaceCulling = _module.dwrap('rlDisableBackfaceCulling', []);
    rlColorMask = _module.dwrap('rlColorMask', [n, n, n, n]);
    rlSetCullFace = _module.dwrap('rlSetCullFace', [n]);
    rlEnableScissorTest = _module.dwrap('rlEnableScissorTest', []);
    rlDisableScissorTest = _module.dwrap('rlDisableScissorTest', []);
    rlScissor = _module.dwrap('rlScissor', [n, n, n, n]);
    rlEnableWireMode = _module.dwrap('rlEnableWireMode', []);
    rlEnablePointMode = _module.dwrap('rlEnablePointMode', []);
    rlDisableWireMode = _module.dwrap('rlDisableWireMode', []);
    rlSetLineWidth = _module.dwrap('rlSetLineWidth', [n]);
    rlGetLineWidth = _module.dwrap('rlGetLineWidth', [], n);
    rlEnableSmoothLines = _module.dwrap('rlEnableSmoothLines', []);
    rlDisableSmoothLines = _module.dwrap('rlDisableSmoothLines', []);
    rlEnableStereoRender = _module.dwrap('rlEnableStereoRender', []);
    rlDisableStereoRender = _module.dwrap('rlDisableStereoRender', []);
    rlIsStereoRenderEnabled = _module.dwrap('rlIsStereoRenderEnabled', [], n);
    rlClearColor = _module.dwrap('rlClearColor', [n, n, n, n]);
    rlClearScreenBuffers = _module.dwrap('rlClearScreenBuffers', []);
    rlCheckErrors = _module.dwrap('rlCheckErrors', []);
    rlSetBlendMode = _module.dwrap('rlSetBlendMode', [n]);
    rlSetBlendFactors = _module.dwrap('rlSetBlendFactors', [n, n, n]);
    rlSetBlendFactorsSeparate = _module.dwrap('rlSetBlendFactorsSeparate', [n, n, n, n, n, n]);
    rlglInit = _module.dwrap('rlglInit', [n, n]);
    rlglClose = _module.dwrap('rlglClose', []);
    rlLoadExtensions = _module.dwrap('rlLoadExtensions', [n]);
    rlGetVersion = _module.dwrap('rlGetVersion', [], n);
    rlSetFramebufferWidth = _module.dwrap('rlSetFramebufferWidth', [n]);
    rlGetFramebufferWidth = _module.dwrap('rlGetFramebufferWidth', [], n);
    rlSetFramebufferHeight = _module.dwrap('rlSetFramebufferHeight', [n]);
    rlGetFramebufferHeight = _module.dwrap('rlGetFramebufferHeight', [], n);
    rlGetTextureIdDefault = _module.dwrap('rlGetTextureIdDefault', [], n);
    rlGetShaderIdDefault = _module.dwrap('rlGetShaderIdDefault', [], n);
    rlGetShaderLocsDefault = _module.dwrap('rlGetShaderLocsDefault', [], n);
    rlLoadRenderBatch = _module.dwrap('rlLoadRenderBatch', [n, n, n]);
    rlUnloadRenderBatch = _module.dwrap('rlUnloadRenderBatch', [n]);
    rlDrawRenderBatch = _module.dwrap('rlDrawRenderBatch', [n]);
    rlSetRenderBatchActive = _module.dwrap('rlSetRenderBatchActive', [n]);
    rlDrawRenderBatchActive = _module.dwrap('rlDrawRenderBatchActive', []);
    rlCheckRenderBatchLimit = _module.dwrap('rlCheckRenderBatchLimit', [n], n);
    rlSetTexture = _module.dwrap('rlSetTexture', [n]);
    rlLoadVertexArray = _module.dwrap('rlLoadVertexArray', [], n);
    rlLoadVertexBuffer = _module.dwrap('rlLoadVertexBuffer', [n, n, n]);
    rlLoadVertexBufferElement = _module.dwrap('rlLoadVertexBufferElement', [n, n, n], n);
    rlUpdateVertexBuffer = _module.dwrap('rlUpdateVertexBuffer', [n, n, n, n]);
    rlUpdateVertexBufferElements = _module.dwrap('rlUpdateVertexBufferElements', [n, n, n, n]);
    rlUnloadVertexArray = _module.dwrap('rlUnloadVertexArray', [n]);
    rlUnloadVertexBuffer = _module.dwrap('rlUnloadVertexBuffer', [n]);
    rlSetVertexAttribute = _module.dwrap('rlSetVertexAttribute', [n, n, n, n, n, n]);
    rlSetVertexAttributeDivisor = _module.dwrap('rlSetVertexAttributeDivisor', [n, n]);
    rlSetVertexAttributeDefault = _module.dwrap('rlSetVertexAttributeDefault', [n, n, n, n]);
    rlDrawVertexArray = _module.dwrap('rlDrawVertexArray', [n, n]);
    rlDrawVertexArrayElements = _module.dwrap('rlDrawVertexArrayElements', [n, n, n]);
    rlDrawVertexArrayInstanced = _module.dwrap('rlDrawVertexArrayInstanced', [n, n, n]);
    rlDrawVertexArrayElementsInstanced = _module.dwrap('rlDrawVertexArrayElementsInstanced', [n, n, n, n]);
    rlLoadTexture = _module.dwrap('rlLoadTexture', [n, n, n, n, n]);
    rlLoadTextureDepth = _module.dwrap('rlLoadTextureDepth', [n, n, n], n);
    rlLoadTextureCubemap = _module.dwrap('rlLoadTextureCubemap', [n, n, n, n]);
    rlUpdateTexture = _module.dwrap('rlUpdateTexture', [n, n, n, n, n, n, n]);
    rlGetGlTextureFormats = _module.dwrap('rlGetGlTextureFormats', [n, n, n, n]);
    rlGetPixelFormatName = _module.dwrap('rlGetPixelFormatName', [n], n);
    rlUnloadTexture = _module.dwrap('rlUnloadTexture', [n]);
    rlGenTextureMipmaps = _module.dwrap('rlGenTextureMipmaps', [n, n, n, n, n]);
    rlReadTexturePixels = _module.dwrap('rlReadTexturePixels', [n, n, n, n], n);
    rlReadScreenPixels = _module.dwrap('rlReadScreenPixels', [n, n], n);
    rlLoadFramebuffer = _module.dwrap('rlLoadFramebuffer', [], n);
    rlFramebufferAttach = _module.dwrap('rlFramebufferAttach', [n, n, n, n, n]);
    rlFramebufferComplete = _module.dwrap('rlFramebufferComplete', [n], n);
    rlUnloadFramebuffer = _module.dwrap('rlUnloadFramebuffer', [n]);
    rlLoadShaderCode = _module.dwrap('rlLoadShaderCode', [s, s], n);
    rlCompileShader = _module.dwrap('rlCompileShader', [s, n], n);
    rlLoadShaderProgram = _module.dwrap('rlLoadShaderProgram', [n, n], n);
    rlUnloadShaderProgram = _module.dwrap('rlUnloadShaderProgram', [n]);
    rlGetLocationUniform = _module.dwrap('rlGetLocationUniform', [n, s]);
    rlGetLocationAttrib = _module.dwrap('rlGetLocationAttrib', [n, s], n);
    rlSetUniform = _module.dwrap('rlSetUniform', [n, n, n, n]);
    rlSetUniformMatrix = _module.dwrap('rlSetUniformMatrix', [n, n]);
    rlSetUniformMatrices = _module.dwrap('rlSetUniformMatrices', [n, n, n]);
    rlSetUniformSampler = _module.dwrap('rlSetUniformSampler', [n, n]);
    rlSetShader = _module.dwrap('rlSetShader', [n, n]);
    rlLoadComputeShaderProgram = _module.dwrap('rlLoadComputeShaderProgram', [n], n);
    rlComputeShaderDispatch = _module.dwrap('rlComputeShaderDispatch', [n, n, n]);
    rlLoadShaderBuffer = _module.dwrap('rlLoadShaderBuffer', [n, n, n], n);
    rlUnloadShaderBuffer = _module.dwrap('rlUnloadShaderBuffer', [n]);
    rlUpdateShaderBuffer = _module.dwrap('rlUpdateShaderBuffer', [n, n, n, n]);
    rlBindShaderBuffer = _module.dwrap('rlBindShaderBuffer', [n, n]);
    rlReadShaderBuffer = _module.dwrap('rlReadShaderBuffer', [n, n, n, n]);
    rlCopyShaderBuffer = _module.dwrap('rlCopyShaderBuffer', [n, n, n, n, n]);
    rlGetShaderBufferSize = _module.dwrap('rlGetShaderBufferSize', [n], n);
    rlBindImageTexture = _module.dwrap('rlBindImageTexture', [n, n, n, n]);
    rlGetMatrixModelview = _module.dwrap('rlGetMatrixModelview', [n]);
    rlGetMatrixProjection = _module.dwrap('rlGetMatrixProjection', [n]);
    rlGetMatrixTransform = _module.dwrap('rlGetMatrixTransform', [n]);
    rlGetMatrixProjectionStereo = _module.dwrap('rlGetMatrixProjectionStereo', [n, n]);
    rlGetMatrixViewOffsetStereo = _module.dwrap('rlGetMatrixViewOffsetStereo', [n, n]);
    rlSetMatrixProjection = _module.dwrap('rlSetMatrixProjection', [n]);
    rlSetMatrixModelview = _module.dwrap('rlSetMatrixModelview', [n]);
    rlSetMatrixProjectionStereo = _module.dwrap('rlSetMatrixProjectionStereo', [n, n]);
    rlSetMatrixViewOffsetStereo = _module.dwrap('rlSetMatrixViewOffsetStereo', [n, n]);
    rlLoadDrawCube = _module.dwrap('rlLoadDrawCube', []);
    rlLoadDrawQuad = _module.dwrap('rlLoadDrawQuad', []);
  }
}