part of '../../../raylib_dartified_web.dart';

class RaylibGui extends RaylibModuleWasm with RaylibGuiModuleExtras<Raylib> {
  late final JSFunction GuiEnable;
  late final JSFunction GuiDisable;
  late final JSFunction GuiLock;
  late final JSFunction GuiUnlock;
  late final JSFunction GuiIsLocked;
  late final JSFunction GuiSetAlpha;
  late final JSFunction GuiSetState;
  late final JSFunction GuiGetState;
  late final JSFunction GuiSetFont;
  late final JSFunction GuiGetFont;
  late final JSFunction GuiSetStyle;
  late final JSFunction GuiGetStyle;
  late final JSFunction GuiLoadStyle;
  late final JSFunction GuiLoadStyleDefault;
  late final JSFunction GuiEnableTooltip;
  late final JSFunction GuiDisableTooltip;
  late final JSFunction GuiSetTooltip;
  late final JSFunction GuiIconText;
  late final JSFunction GuiSetIconScale;
  late final JSFunction GuiGetIcons;
  late final JSFunction GuiLoadIcons;
  late final JSFunction GuiDrawIcon;
  late final JSFunction GuiGetTextWidth;
  late final JSFunction GuiWindowBox;
  late final JSFunction GuiGroupBox;
  late final JSFunction GuiLine;
  late final JSFunction GuiPanel;
  late final JSFunction GuiTabBar;
  late final JSFunction GuiScrollPanel;
  late final JSFunction GuiLabel;
  late final JSFunction GuiButton;
  late final JSFunction GuiLabelButton;
  late final JSFunction GuiToggle;
  late final JSFunction GuiToggleGroup;
  late final JSFunction GuiToggleSlider;
  late final JSFunction GuiCheckBox;
  late final JSFunction GuiComboBox;
  late final JSFunction GuiDropdownBox;
  late final JSFunction GuiSpinner;
  late final JSFunction GuiValueBox;
  late final JSFunction GuiValueBoxFloat;
  late final JSFunction GuiTextBox;
  late final JSFunction GuiSlider;
  late final JSFunction GuiSliderBar;
  late final JSFunction GuiProgressBar;
  late final JSFunction GuiStatusBar;
  late final JSFunction GuiDummyRec;
  late final JSFunction GuiGrid;
  late final JSFunction GuiListView;
  late final JSFunction GuiListViewEx;
  late final JSFunction GuiMessageBox;
  late final JSFunction GuiTextInputBox;
  late final JSFunction GuiColorPicker;
  late final JSFunction GuiColorPanel;
  late final JSFunction GuiColorBarAlpha;
  late final JSFunction GuiColorBarHue;
  late final JSFunction GuiColorPickerHSV;
  late final JSFunction GuiColorPanelHSV;

  RaylibGui(super.rl) {
    GuiEnable           = _module.dwrap('GuiEnable',           []);
    GuiDisable          = _module.dwrap('GuiDisable',          []);
    GuiLock             = _module.dwrap('GuiLock',             []);
    GuiUnlock           = _module.dwrap('GuiUnlock',           []);
    GuiIsLocked         = _module.dwrap('GuiIsLocked',         [], n);
    GuiSetAlpha         = _module.dwrap('GuiSetAlpha',         [n]);
    GuiSetState         = _module.dwrap('GuiSetState',         [n]);
    GuiGetState         = _module.dwrap('GuiGetState',         [], n);
    GuiSetFont          = _module.dwrap('GuiSetFont',          [n]);
    GuiGetFont          = _module.dwrap('GuiGetFont',          [n]);
    GuiSetStyle         = _module.dwrap('GuiSetStyle',         [n, n, n]);
    GuiGetStyle         = _module.dwrap('GuiGetStyle',         [n, n], n);
    GuiLoadStyle        = _module.dwrap('GuiLoadStyle',        [n]);
    GuiLoadStyleDefault = _module.dwrap('GuiLoadStyleDefault', []);
    GuiEnableTooltip    = _module.dwrap('GuiEnableTooltip',    []);
    GuiDisableTooltip   = _module.dwrap('GuiDisableTooltip',   []);
    GuiSetTooltip       = _module.dwrap('GuiSetTooltip',       [n]);
    GuiIconText         = _module.dwrap('GuiIconText',         [n, n], n);
    GuiSetIconScale     = _module.dwrap('GuiSetIconScale',     [n]);
    GuiGetIcons         = _module.dwrap('GuiGetIcons',         [], n);
    GuiLoadIcons        = _module.dwrap('GuiLoadIcons',        [n, n], n);
    GuiDrawIcon         = _module.dwrap('GuiDrawIcon',         [n, n, n, n, n]);
    GuiGetTextWidth     = _module.dwrap('GuiGetTextWidth',     [n], n);
    GuiWindowBox        = _module.dwrap('GuiWindowBox',        [n, n]);
    GuiGroupBox         = _module.dwrap('GuiGroupBox',         [n, n], n);
    GuiLine             = _module.dwrap('GuiLine',             [n, n], n);
    GuiPanel            = _module.dwrap('GuiPanel',            [n, n], n);
    GuiTabBar           = _module.dwrap('GuiTabBar',           [n, n, n, n], n);
    GuiScrollPanel      = _module.dwrap('GuiScrollPanel',      [n, n, n, n, n], n);
    GuiLabel            = _module.dwrap('GuiLabel',            [n, n], n);
    GuiButton           = _module.dwrap('GuiButton',           [n, n], n);
    GuiLabelButton      = _module.dwrap('GuiLabelButton',      [n, n], n);
    GuiToggle           = _module.dwrap('GuiToggle',           [n, n, n], n);
    GuiToggleGroup      = _module.dwrap('GuiToggleGroup',      [n, n, n], n);
    GuiToggleSlider     = _module.dwrap('GuiToggleSlider',     [n, n, n], n);
    GuiCheckBox         = _module.dwrap('GuiCheckBox',         [n, n, n], n);
    GuiComboBox         = _module.dwrap('GuiComboBox',         [n, n, n], n);
    GuiDropdownBox      = _module.dwrap('GuiDropdownBox',      [n, n, n, n], n);
    GuiSpinner          = _module.dwrap('GuiSpinner',          [n, n, n, n, n, n], n);
    GuiValueBox         = _module.dwrap('GuiValueBox',         [n, n, n, n, n, n], n);
    GuiValueBoxFloat    = _module.dwrap('GuiValueBoxFloat',    [n, n, n, n, n], n);
    GuiTextBox          = _module.dwrap('GuiTextBox',          [n, n, n, n], n);
    GuiSlider           = _module.dwrap('GuiSlider',           [n, n, n, n, n, n], n);
    GuiSliderBar        = _module.dwrap('GuiSliderBar',        [n, n, n, n, n, n]);
    GuiProgressBar      = _module.dwrap('GuiProgressBar',      [n, n, n, n, n, n], n);
    GuiStatusBar        = _module.dwrap('GuiStatusBar',        [n, n], n);
    GuiDummyRec         = _module.dwrap('GuiDummyRec',         [n, n], n);
    GuiGrid             = _module.dwrap('GuiGrid',             [n, n, n, n, n], n);
    GuiListView         = _module.dwrap('GuiListView',         [n, n, n, n], n);
    GuiListViewEx       = _module.dwrap('GuiListViewEx',       [n, n, n, n, n, n], n);
    GuiMessageBox       = _module.dwrap('GuiMessageBox',       [n, n, n, n], n);
    GuiTextInputBox     = _module.dwrap('GuiTextInputBox',     [n, n, n, n, n, n, n], n);
    GuiColorPicker      = _module.dwrap('GuiColorPicker',      [n, n, n], n);
    GuiColorPanel       = _module.dwrap('GuiColorPanel',       [n, n, n], n);
    GuiColorBarAlpha    = _module.dwrap('GuiColorBarAlpha',    [n, n, n], n);
    GuiColorBarHue      = _module.dwrap('GuiColorBarHue',      [n, n, n], n);
    GuiColorPickerHSV   = _module.dwrap('GuiColorPickerHSV',   [n, n, n], n);
    GuiColorPanelHSV    = _module.dwrap('GuiColorPanelHSV',    [n, n, n], n);
  }
}