// Example dartified, see original for reference:
// https://github.com/raysan5/raylib/blob/master/examples/textures/textures_raw_data.c
// WARNING: expects resources from the raylib source
import '../base_dart.dart';

const int screenWidth = 800;
const int screenHeight = 450;

void main() => Raylib((rl) {
  InitWindow(screenWidth, screenHeight, "textures_raw_data");
  SetTargetFPS(60);

  final fudesumiRaw = LoadImageRaw(
    "../resources/fudesumi.raw",
    384, 512, .PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0
  );
  final fudesumi = LoadTextureFromImage(fudesumiRaw);
  UnloadImage(fudesumiRaw);

  int width = 960;
  int height = 480;

  final List<ColorD> pixels = .generate(width*height, (_) => .BLACK);

  for (int y = 0; y < height; y++)
  {
    for (int x = 0; x < width; x++)
    {
      if (((x~/32+y~/32)/1)%2 == 0) pixels[y*width + x] = .ORANGE;
      else pixels[y*width + x] = .GOLD;
    }
  }

  final checkedIm = ImageD(
    data: .fromList(pixels.expand((p) => [p.r, p.g, p.b, p.a]).toList()),
    width: width,
    height: height,
    format: .PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
    mipmaps: 1,
  );

  final checked = LoadTextureFromImage(checkedIm);
  
  UnloadImage(checkedIm);

  rl.setMainLoop(() {
    BeginDrawing();

      ClearBackground(.RAYWHITE);

      DrawTexture(
        checked,
        screenWidth/2 - checked.width/2,
        screenHeight/2 - checked.height/2,
        Fade(.WHITE, 0.5)
      );
      
      DrawTexture(fudesumi, 430, -30, .WHITE);

      DrawText(
        "CHECKED TEXTURE ",
        84, 85, 30, .BROWN
      );
      DrawText(
        "GENERATED by CODE",
        72, 148, 30, .BROWN
      );
      DrawText(
        "and RAW IMAGE LOADING",
        46, 210, 30, .BROWN
      );

      DrawText(
        "(c) Fudesumi sprite by Eiden Marsal",
        310, screenHeight - 20, 10, .BROWN
      );

    EndDrawing();
  });
});