// Example dartified, see original for reference:
// https://github.com/raysan5/raylib/blob/master/examples/textures/textures_raw_data.c
// WARNING: expects resources from the raylib source
import 'package:raylib_dartified_web/raylib_dartified_web.dart';

const int screenWidth = 800;
const int screenHeight = 450;

void main() => Raylib((rl) {

  rl.CoreD.InitWindow(screenWidth, screenHeight, "textures_raw_data");
  rl.CoreD.SetWindowMonitor(0);
  rl.CoreD.SetTargetFPS(60);

  final fudesumiRaw = rl.CoreD.LoadImageRaw(
    "./resources/fudesumi.raw",
    384, 512, .PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0
  );
  final fudesumi = rl.CoreD.LoadTextureFromImage(fudesumiRaw);
  rl.CoreD.UnloadImage(fudesumiRaw);

  int width = 960;
  int height = 480;

  final List<ColorD> pixels = .generate(width*height, (_) => .BLACK);

  for (int y = 0; y < height; y++)
  {
    for (int x = 0; x < width; x++)
    {
      if (((x~/32+y~/32)/1)%2 == 0) pixels[y*width + x] = .ORANGE;
      else pixels[y*width + x] = .GOLD;
    }
  }

  final checkedIm = ImageD(
    data: .fromList(pixels.expand((p) => [p.r, p.g, p.b, p.a]).toList()),
    width: width,
    height: height,
    format: .PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
    mipmaps: 1,
  );

  final checked = rl.CoreD.LoadTextureFromImage(checkedIm);
  
  rl.CoreD.UnloadImage(checkedIm);

  rl.setMainLoop(() {
    rl.CoreD.BeginDrawing();

      rl.CoreD.ClearBackground(.RAYWHITE);

      rl.CoreD.DrawTexture(
        checked,
        screenWidth/2 - checked.width/2,
        screenHeight/2 - checked.height/2,
        rl.CoreD.Fade(.WHITE, 0.5)
      );
      
      rl.CoreD.DrawTexture(fudesumi, 430, -30, .WHITE);

      rl.CoreD.DrawText(
        "CHECKED TEXTURE ",
        84, 85, 30, .BROWN
      );
      rl.CoreD.DrawText(
        "GENERATED by CODE",
        72, 148, 30, .BROWN
      );
      rl.CoreD.DrawText(
        "and RAW IMAGE LOADING",
        46, 210, 30, .BROWN
      );

      rl.CoreD.DrawText(
        "(c) Fudesumi sprite by Eiden Marsal",
        310, screenHeight - 20, 10, .BROWN
      );

    rl.CoreD.EndDrawing();
  });
});