part of '../../raylib_dartified_web.dart';

class RaylibAudio extends RaylibModuleWasm {
  late final JSFunction InitAudioDevice;
  late final JSFunction CloseAudioDevice;
  late final JSFunction IsAudioDeviceReady;
  late final JSFunction SetMasterVolume;
  late final JSFunction GetMasterVolume;
  late final JSFunction LoadWave;
  late final JSFunction LoadWaveFromMemory;
  late final JSFunction IsWaveValid;
  late final JSFunction LoadSound;
  late final JSFunction LoadSoundFromWave;
  late final JSFunction LoadSoundAlias;
  late final JSFunction IsSoundValid;
  late final JSFunction UpdateSound;
  late final JSFunction UnloadWave;
  late final JSFunction UnloadSound;
  late final JSFunction UnloadSoundAlias;
  late final JSFunction ExportWave;
  late final JSFunction ExportWaveAsCode;
  late final JSFunction PlaySound;
  late final JSFunction StopSound;
  late final JSFunction PauseSound;
  late final JSFunction ResumeSound;
  late final JSFunction IsSoundPlaying;
  late final JSFunction SetSoundVolume;
  late final JSFunction SetSoundPitch;
  late final JSFunction SetSoundPan;
  late final JSFunction WaveCopy;
  late final JSFunction WaveCrop;
  late final JSFunction WaveFormat;
  late final JSFunction LoadWaveSamples;
  late final JSFunction UnloadWaveSamples;
  late final JSFunction LoadMusicStream;
  late final JSFunction LoadMusicStreamFromMemory;
  late final JSFunction IsMusicValid;
  late final JSFunction UnloadMusicStream;
  late final JSFunction PlayMusicStream;
  late final JSFunction IsMusicStreamPlaying;
  late final JSFunction UpdateMusicStream;
  late final JSFunction StopMusicStream;
  late final JSFunction PauseMusicStream;
  late final JSFunction ResumeMusicStream;
  late final JSFunction SeekMusicStream;
  late final JSFunction SetMusicVolume;
  late final JSFunction SetMusicPitch;
  late final JSFunction SetMusicPan;
  late final JSFunction GetMusicTimeLength;
  late final JSFunction GetMusicTimePlayed;
  late final JSFunction LoadAudioStream;
  late final JSFunction IsAudioStreamValid;
  late final JSFunction UnloadAudioStream;
  late final JSFunction UpdateAudioStream;
  late final JSFunction IsAudioStreamProcessed;
  late final JSFunction PlayAudioStream;
  late final JSFunction PauseAudioStream;
  late final JSFunction ResumeAudioStream;
  late final JSFunction IsAudioStreamPlaying;
  late final JSFunction StopAudioStream;
  late final JSFunction SetAudioStreamVolume;
  late final JSFunction SetAudioStreamPitch;
  late final JSFunction SetAudioStreamPan;
  late final JSFunction SetAudioStreamBufferSizeDefault;
  late final JSFunction SetAudioStreamCallback;
  late final JSFunction AttachAudioStreamProcessor;
  late final JSFunction DetachAudioStreamProcessor;
  late final JSFunction AttachAudioMixedProcessor;
  late final JSFunction DetachAudioMixedProcessor;

  RaylibAudio(super.rl) {
    InitAudioDevice = _module.dwrap('InitAudioDevice', []);
    CloseAudioDevice = _module.dwrap('CloseAudioDevice', []);
    IsAudioDeviceReady = _module.dwrap('IsAudioDeviceReady', [], n);
    SetMasterVolume = _module.dwrap('SetMasterVolume', [n]);
    GetMasterVolume = _module.dwrap('GetMasterVolume', [], n);
    LoadWave = _module.dwrap('LoadWave', [n, s]);
    LoadWaveFromMemory = _module.dwrap('LoadWaveFromMemory', [n, s, n, n]);
    IsWaveValid = _module.dwrap('IsWaveValid', [n], n);
    LoadSound = _module.dwrap('LoadSound', [n, s]);
    LoadSoundFromWave = _module.dwrap('LoadSoundFromWave', [n, n]);
    LoadSoundAlias = _module.dwrap('LoadSoundAlias', [n, n]);
    IsSoundValid = _module.dwrap('IsSoundValid', [n], n);
    UpdateSound = _module.dwrap('UpdateSound', [n, n, n]);
    UnloadWave = _module.dwrap('UnloadWave', [n]);
    UnloadSound = _module.dwrap('UnloadSound', [n]);
    UnloadSoundAlias = _module.dwrap('UnloadSoundAlias', [n]);
    ExportWave = _module.dwrap('ExportWave', [n, s], n);
    ExportWaveAsCode = _module.dwrap('ExportWaveAsCode', [n, s], n);
    PlaySound = _module.dwrap('PlaySound', [n]);
    StopSound = _module.dwrap('StopSound', [n]);
    PauseSound = _module.dwrap('PauseSound', [n]);
    ResumeSound = _module.dwrap('ResumeSound', [n]);
    IsSoundPlaying = _module.dwrap('IsSoundPlaying', [n], n);
    SetSoundVolume = _module.dwrap('SetSoundVolume', [n, n]);
    SetSoundPitch = _module.dwrap('SetSoundPitch', [n, n]);
    SetSoundPan = _module.dwrap('SetSoundPan', [n, n]);
    WaveCopy = _module.dwrap('WaveCopy', [n, n]);
    WaveCrop = _module.dwrap('WaveCrop', [n, n, n]);
    WaveFormat = _module.dwrap('WaveFormat', [n, n, n, n]);
    LoadWaveSamples = _module.dwrap('LoadWaveSamples', [n], n);
    UnloadWaveSamples = _module.dwrap('UnloadWaveSamples', [n]);
    LoadMusicStream = _module.dwrap('LoadMusicStream', [n, s]);
    LoadMusicStreamFromMemory = _module.dwrap('LoadMusicStreamFromMemory', [n, s, n, n]);
    IsMusicValid = _module.dwrap('IsMusicValid', [n], n);
    UnloadMusicStream = _module.dwrap('UnloadMusicStream', [n]);
    PlayMusicStream = _module.dwrap('PlayMusicStream', [n]);
    IsMusicStreamPlaying = _module.dwrap('IsMusicStreamPlaying', [n], n);
    UpdateMusicStream = _module.dwrap('UpdateMusicStream', [n]);
    StopMusicStream = _module.dwrap('StopMusicStream', [n]);
    PauseMusicStream = _module.dwrap('PauseMusicStream', [n]);
    ResumeMusicStream = _module.dwrap('ResumeMusicStream', [n]);
    SeekMusicStream = _module.dwrap('SeekMusicStream', [n, n]);
    SetMusicVolume = _module.dwrap('SetMusicVolume', [n, n]);
    SetMusicPitch = _module.dwrap('SetMusicPitch', [n, n]);
    SetMusicPan = _module.dwrap('SetMusicPan', [n, n]);
    GetMusicTimeLength = _module.dwrap('GetMusicTimeLength', [n], n);
    GetMusicTimePlayed = _module.dwrap('GetMusicTimePlayed', [n], n);
    LoadAudioStream = _module.dwrap('LoadAudioStream', [n, n, n, n]);
    IsAudioStreamValid = _module.dwrap('IsAudioStreamValid', [n], n);
    UnloadAudioStream = _module.dwrap('UnloadAudioStream', [n]);
    UpdateAudioStream = _module.dwrap('UpdateAudioStream', [n, n, n]);
    IsAudioStreamProcessed = _module.dwrap('IsAudioStreamProcessed', [n], n);
    PlayAudioStream = _module.dwrap('PlayAudioStream', [n]);
    PauseAudioStream = _module.dwrap('PauseAudioStream', [n]);
    ResumeAudioStream = _module.dwrap('ResumeAudioStream', [n]);
    IsAudioStreamPlaying = _module.dwrap('IsAudioStreamPlaying', [n], n);
    StopAudioStream = _module.dwrap('StopAudioStream', [n]);
    SetAudioStreamVolume = _module.dwrap('SetAudioStreamVolume', [n, n]);
    SetAudioStreamPitch = _module.dwrap('SetAudioStreamPitch', [n, n]);
    SetAudioStreamPan = _module.dwrap('SetAudioStreamPan', [n, n]);
    SetAudioStreamBufferSizeDefault = _module.dwrap('SetAudioStreamBufferSizeDefault', [n]);
    SetAudioStreamCallback = _module.dwrap('SetAudioStreamCallback', [n, n]);
    AttachAudioStreamProcessor = _module.dwrap('AttachAudioStreamProcessor', [n, n]);
    DetachAudioStreamProcessor = _module.dwrap('DetachAudioStreamProcessor', [n, n]);
    AttachAudioMixedProcessor = _module.dwrap('AttachAudioMixedProcessor', [n]);
    DetachAudioMixedProcessor = _module.dwrap('DetachAudioMixedProcessor', [n]);
  }
}